/**
 * exercises/cours1-2-exercises.ts
 * Harmonia — Exercices d'identification et de construction pour les cours 1 et 2
 *
 * Cours 1 : gamme, degrés, intervalles → type "identify"
 * Cours 2 : accords, gammes, triades, tétrades, renversements → type "identify" + "build"
 */

import type { IdentifyExercise, BuildExercise } from "@/types/exercise";

// ════════════════════════════════════════════════════════════════════════════
// COURS 1 — Gamme, degrés, intervalles
// ════════════════════════════════════════════════════════════════════════════

export const COURS1_IDENTIFY: IdentifyExercise[] = [
  // ── Degrés ──────────────────────────────────────────────────────────────
  {
    id: "c1-degree-name-1",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["degrés","noms","tonique"],
    concepts: ["degrés de la gamme","nomenclature"],
    question: "Quel est le nom du Ier degré ?",
    options: [
      { id:"a", label:"Tonique",        isCorrect: true  },
      { id:"b", label:"Dominante",      isCorrect: false },
      { id:"c", label:"Sous-dominante", isCorrect: false },
      { id:"d", label:"Sensible",       isCorrect: false },
    ],
    explanation: "Le Ier degré s'appelle Tonique — c'est le centre de gravité de la gamme, le point de repos et de résolution.",
  },
  {
    id: "c1-degree-name-4",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["degrés","noms","sous-dominante"],
    concepts: ["degrés de la gamme","nomenclature"],
    question: "Quel est le nom du IVe degré ?",
    options: [
      { id:"a", label:"Sus-tonique",    isCorrect: false },
      { id:"b", label:"Médiante",       isCorrect: false },
      { id:"c", label:"Sous-dominante", isCorrect: true  },
      { id:"d", label:"Sensible",       isCorrect: false },
    ],
    explanation: "Le IVe degré est la Sous-dominante — il est situé une quinte en dessous de la dominante (V), d'où son nom.",
  },
  {
    id: "c1-degree-name-7",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["degrés","noms","sensible"],
    concepts: ["degrés de la gamme","sensible","attraction"],
    question: "Quel est le nom du VIIe degré ?",
    options: [
      { id:"a", label:"Sus-dominante",  isCorrect: false },
      { id:"b", label:"Sensible",       isCorrect: true  },
      { id:"c", label:"Médiante",       isCorrect: false },
      { id:"d", label:"Dominante",      isCorrect: false },
    ],
    explanation: "Le VIIe degré est la Sensible — à un demi-ton de la tonique, il crée une forte attraction ascendante vers le Ier degré.",
  },
  {
    id: "c1-degree-c-major-6",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["degrés","Do majeur","sus-dominante"],
    concepts: ["degrés","transposition contextuelle"],
    question: "En Do majeur, quel est le VIe degré ?",
    context: "Gamme de Do majeur : C – D – E – F – G – A – B",
    options: [
      { id:"a", label:"F",  isCorrect: false },
      { id:"b", label:"G",  isCorrect: false },
      { id:"c", label:"A",  isCorrect: true  },
      { id:"d", label:"B",  isCorrect: false },
    ],
    explanation: "C(I) D(II) E(III) F(IV) G(V) A(VI) B(VII). Le VIe degré de Do majeur est A (La) — la sus-dominante.",
  },
  {
    id: "c1-degree-g-major-5",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["degrés","Sol majeur","dominante"],
    concepts: ["degrés","transposition"],
    question: "En Sol majeur, quel est le Ve degré (la dominante) ?",
    context: "Gamme de Sol majeur : G – A – B – C – D – E – F#",
    options: [
      { id:"a", label:"C",  isCorrect: false },
      { id:"b", label:"D",  isCorrect: true  },
      { id:"c", label:"E",  isCorrect: false },
      { id:"d", label:"F#", isCorrect: false },
    ],
    explanation: "G(I) A(II) B(III) C(IV) D(V). La dominante de Sol majeur est D (Ré).",
  },
  {
    id: "c1-degree-f-major-7",
    type: "identify",
    cours: 1, difficulty: 2,
    tags: ["degrés","Fa majeur","sensible"],
    concepts: ["sensible","gammes avec bémols"],
    question: "En Fa majeur, quelle est la sensible (VIIe degré) ?",
    context: "Gamme de Fa majeur : F – G – A – Bb – C – D – E",
    options: [
      { id:"a", label:"D",  isCorrect: false },
      { id:"b", label:"Bb", isCorrect: false },
      { id:"c", label:"E",  isCorrect: true  },
      { id:"d", label:"C",  isCorrect: false },
    ],
    explanation: "F(I) G(II) A(III) Bb(IV) C(V) D(VI) E(VII). La sensible de Fa majeur est E (Mi) — à un demi-ton sous F.",
  },
  // ── Intervalles ──────────────────────────────────────────────────────────
  {
    id: "c1-interval-name-ce",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["intervalles","tierce","nom"],
    concepts: ["nom de l'intervalle","degrés diatoniques"],
    question: "Quel est le nom de l'intervalle C – E ?",
    context: "C → D → E",
    options: [
      { id:"a", label:"Seconde",  isCorrect: false },
      { id:"b", label:"Tierce",   isCorrect: true  },
      { id:"c", label:"Quarte",   isCorrect: false },
      { id:"d", label:"Quinte",   isCorrect: false },
    ],
    explanation: "C(1) – D(2) – E(3) : on compte 3 degrés inclusivement → Tierce.",
    hint: "On compte les degrés inclusivements, en incluant les deux notes extrêmes.",
  },
  {
    id: "c1-interval-quality-ce",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["intervalles","tierce majeure","nature"],
    concepts: ["nature de l'intervalle","demi-tons"],
    question: "Quelle est la nature de l'intervalle C – E ?",
    context: "C → C# → D → D# → E  (4 demi-tons)",
    options: [
      { id:"a", label:"Tierce diminuée",  isCorrect: false },
      { id:"b", label:"Tierce mineure",   isCorrect: false },
      { id:"c", label:"Tierce majeure",   isCorrect: true  },
      { id:"d", label:"Tierce augmentée", isCorrect: false },
    ],
    explanation: "C–E = 4 demi-tons = tierce majeure. La tierce mineure (E–G par exemple) = 3 demi-tons.",
  },
  {
    id: "c1-interval-quality-eg",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["intervalles","tierce mineure"],
    concepts: ["nature de l'intervalle","demi-tons"],
    question: "Quelle est la nature de l'intervalle E – G ?",
    context: "E → F → F# → G  (3 demi-tons)",
    options: [
      { id:"a", label:"Tierce diminuée",  isCorrect: false },
      { id:"b", label:"Tierce mineure",   isCorrect: true  },
      { id:"c", label:"Tierce majeure",   isCorrect: false },
      { id:"d", label:"Tierce augmentée", isCorrect: false },
    ],
    explanation: "E–G = 3 demi-tons = tierce mineure. Attention : E–F = ½ ton seulement (pas de touche noire entre Mi et Fa).",
  },
  {
    id: "c1-interval-tritone",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["intervalles","triton","quarte augmentée"],
    concepts: ["triton","instabilité","tension harmonique"],
    question: "Combien de demi-tons contient le triton ?",
    options: [
      { id:"a", label:"4 demi-tons", isCorrect: false },
      { id:"b", label:"5 demi-tons", isCorrect: false },
      { id:"c", label:"6 demi-tons", isCorrect: true  },
      { id:"d", label:"7 demi-tons", isCorrect: false },
    ],
    explanation: "Le triton = 3 tons = 6 demi-tons. Il divise l'octave en deux parties égales — d'où son instabilité acoustique.",
  },
  {
    id: "c1-interval-tritone-notes",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["triton","Do majeur","fonctions"],
    concepts: ["triton","IVe et VIIe degrés"],
    question: "En Do majeur, quelles notes forment le triton fonctionnel ?",
    context: "Gamme : C – D – E – F – G – A – B",
    options: [
      { id:"a", label:"C et G",  isCorrect: false },
      { id:"b", label:"F et B",  isCorrect: true  },
      { id:"c", label:"G et D",  isCorrect: false },
      { id:"d", label:"D et A",  isCorrect: false },
    ],
    explanation: "F (IVe degré, sous-dominante) et B (VIIe degré, sensible) forment le triton de Do majeur. Ce sont les deux notes de G7.",
  },
  {
    id: "c1-interval-fifth",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["intervalles","quinte juste","rapport acoustique"],
    concepts: ["quinte juste","consonance","rapport 3/2"],
    question: "Combien de demi-tons contient une quinte juste ?",
    options: [
      { id:"a", label:"5 demi-tons", isCorrect: false },
      { id:"b", label:"6 demi-tons", isCorrect: false },
      { id:"c", label:"7 demi-tons", isCorrect: true  },
      { id:"d", label:"8 demi-tons", isCorrect: false },
    ],
    explanation: "La quinte juste = 7 demi-tons. Rapport de fréquence 3/2 — la seconde consonance fondamentale après l'octave.",
  },
  {
    id: "c1-interval-inversion",
    type: "identify",
    cours: 1, difficulty: 2,
    tags: ["intervalles","inversions"],
    concepts: ["inversions d'intervalles","règle des 9"],
    question: "L'inversion d'une tierce majeure donne :",
    options: [
      { id:"a", label:"Sixte majeure",  isCorrect: false },
      { id:"b", label:"Sixte mineure",  isCorrect: true  },
      { id:"c", label:"Quinte juste",   isCorrect: false },
      { id:"d", label:"Septième majeure",isCorrect: false },
    ],
    explanation: "Règle des 9 : 3 + 6 = 9. La nature s'inverse : majeure ↔ mineure. Tierce majeure → Sixte mineure.",
  },
  {
    id: "c1-interval-inversion-fifth",
    type: "identify",
    cours: 1, difficulty: 2,
    tags: ["intervalles","inversions","quinte"],
    concepts: ["inversions","juste reste juste"],
    question: "L'inversion d'une quinte juste donne :",
    options: [
      { id:"a", label:"Quarte diminuée",  isCorrect: false },
      { id:"b", label:"Quarte juste",     isCorrect: true  },
      { id:"c", label:"Sixte majeure",    isCorrect: false },
      { id:"d", label:"Tierce majeure",   isCorrect: false },
    ],
    explanation: "5 + 4 = 9. La nature juste reste juste. Quinte juste (7 dt) → Quarte juste (5 dt).",
  },
  {
    id: "c1-scale-structure",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["gamme majeure","tons demi-tons","structure"],
    concepts: ["structure de la gamme majeure","T et ½T"],
    question: "Quelle est la structure de la gamme majeure en tons (T) et demi-tons (½T) ?",
    options: [
      { id:"a", label:"T T T ½T T T ½T",        isCorrect: false },
      { id:"b", label:"T T ½T T T T ½T",         isCorrect: true  },
      { id:"c", label:"T ½T T T T ½T T",         isCorrect: false },
      { id:"d", label:"T T ½T T T ½T T",         isCorrect: false },
    ],
    explanation: "La gamme majeure suit : T–T–½T–T–T–T–½T. Les deux demi-tons sont entre III–IV (Mi–Fa en Do) et VII–VIII (Si–Do).",
  },
  {
    id: "c1-scale-origin",
    type: "identify",
    cours: 1, difficulty: 2,
    tags: ["gamme","origines","cycle des quintes"],
    concepts: ["origines de la gamme","quintes empilées","acoustique"],
    question: "De quel empilement est issue la gamme naturelle ?",
    options: [
      { id:"a", label:"Empilements de tierces", isCorrect: false },
      { id:"b", label:"Empilements de quintes", isCorrect: true  },
      { id:"c", label:"Divisions de l'octave",  isCorrect: false },
      { id:"d", label:"Suite de Fibonacci",      isCorrect: false },
    ],
    explanation: "La gamme diatonique est issue d'empilements de quintes justes (rapport 3/2) : Fa–Do–Sol–Ré–La–Mi–Si, ramenés dans l'octave.",
  },
  {
    id: "c1-enharmonic",
    type: "identify",
    cours: 1, difficulty: 2,
    tags: ["enharmoniques","altérations"],
    concepts: ["enharmoniques","dièse et bémol"],
    question: "C# et Db sont des notes :",
    options: [
      { id:"a", label:"Identiques dans toutes les gammes", isCorrect: false },
      { id:"b", label:"Enharmoniques — même son, noms différents", isCorrect: true },
      { id:"c", label:"À une seconde mineure d'écart",     isCorrect: false },
      { id:"d", label:"Jamais utilisées ensemble",         isCorrect: false },
    ],
    explanation: "C# et Db sont enharmoniques : même hauteur sonore (en tempérament égal), mais noms d'écriture différents selon le contexte tonal.",
  },
  {
    id: "c1-semitone-mifa",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["demi-tons","Mi-Fa","piano"],
    concepts: ["demi-ton naturel","structure chromatique"],
    question: "L'intervalle E – F est :",
    options: [
      { id:"a", label:"1 ton",              isCorrect: false },
      { id:"b", label:"½ ton (demi-ton)",   isCorrect: true  },
      { id:"c", label:"1 ton et demi",      isCorrect: false },
      { id:"d", label:"¼ ton",              isCorrect: false },
    ],
    explanation: "Mi–Fa (E–F) = ½ ton. Il n'y a pas de touche noire entre Mi et Fa sur un piano — c'est un demi-ton naturel, comme Si–Do.",
  },
  {
    id: "c1-interval-sixth-minor",
    type: "identify",
    cours: 1, difficulty: 2,
    tags: ["intervalles","sixte mineure","demi-tons"],
    concepts: ["sixte mineure","inversions"],
    question: "Combien de demi-tons contient une sixte mineure ?",
    options: [
      { id:"a", label:"7", isCorrect: false },
      { id:"b", label:"8", isCorrect: true  },
      { id:"c", label:"9", isCorrect: false },
      { id:"d", label:"10",isCorrect: false },
    ],
    explanation: "Sixte mineure = 8 demi-tons. C'est l'inversion de la tierce majeure (4 + 8 = 12 = octave).",
  },
  {
    id: "c1-degree-number-5",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["degrés","dominante","Ve degré"],
    concepts: ["degrés","nomenclature"],
    question: "Quel est le numéro du degré appelé 'Dominante' ?",
    options: [
      { id:"a", label:"III",  isCorrect: false },
      { id:"b", label:"IV",   isCorrect: false },
      { id:"c", label:"V",    isCorrect: true  },
      { id:"d", label:"VI",   isCorrect: false },
    ],
    explanation: "La Dominante est le Ve degré — situé une quinte au-dessus de la tonique. C'est l'accord de tension maximale.",
  },
  {
    id: "c1-interval-second-major",
    type: "identify",
    cours: 1, difficulty: 1,
    tags: ["intervalles","seconde majeure"],
    concepts: ["seconde majeure","2 demi-tons"],
    question: "Combien de demi-tons contient une seconde majeure ?",
    options: [
      { id:"a", label:"1 demi-ton", isCorrect: false },
      { id:"b", label:"2 demi-tons",isCorrect: true  },
      { id:"c", label:"3 demi-tons",isCorrect: false },
      { id:"d", label:"4 demi-tons",isCorrect: false },
    ],
    explanation: "Seconde majeure = 2 demi-tons (= 1 ton). Ex : C–D, D–E, F–G. C'est l'intervalle du mouvement conjoint.",
  },
];

// ─── Exercices de construction — cours 1 ─────────────────────────────────────

export const COURS1_BUILD: BuildExercise[] = [
  {
    id: "c1-build-scale-c",
    type: "build",
    cours: 1, difficulty: 1,
    tags: ["gamme","Do majeur","construction"],
    concepts: ["gamme majeure","structure T-T-½T-T-T-T-½T"],
    question: "Construis la gamme de Do majeur (7 notes, sans altération)",
    correctNotes: ["C","D","E","F","G","A","B"],
    keySignature: "C",
    explanation: "Do majeur : C D E F G A B. Aucune altération — c'est la gamme de référence. Structure : T–T–½T–T–T–T–½T.",
    hint: "Commence par C et applique la structure T–T–½T–T–T–T–½T.",
  },
  {
    id: "c1-build-scale-g",
    type: "build",
    cours: 1, difficulty: 1,
    tags: ["gamme","Sol majeur","1 dièse"],
    concepts: ["gamme majeure","dièse à la clé"],
    question: "Construis la gamme de Sol majeur (commence sur G)",
    correctNotes: ["G","A","B","C","D","E","F#"],
    keySignature: "G",
    explanation: "Sol majeur : G A B C D E F#. Le F# est nécessaire pour maintenir le ½ ton entre le VIIe et le VIIIe degré.",
    hint: "Applique T–T–½T–T–T–T–½T depuis Sol. Le 7e degré doit être à ½ ton de Sol.",
  },
  {
    id: "c1-build-scale-f",
    type: "build",
    cours: 1, difficulty: 1,
    tags: ["gamme","Fa majeur","1 bémol"],
    concepts: ["gamme majeure","bémol à la clé"],
    question: "Construis la gamme de Fa majeur (commence sur F)",
    correctNotes: ["F","G","A","Bb","C","D","E"],
    keySignature: "F",
    explanation: "Fa majeur : F G A Bb C D E. Le Bb est nécessaire pour le ½ ton entre III et IV (A–Bb = ½ ton).",
    hint: "Le 4e degré doit être à ½ ton du 3e. F–G–A... le 4e degré doit être Bb et non B.",
  },
  {
    id: "c1-build-scale-d",
    type: "build",
    cours: 1, difficulty: 2,
    tags: ["gamme","Ré majeur","2 dièses"],
    concepts: ["gamme majeure","2 dièses"],
    question: "Construis la gamme de Ré majeur",
    correctNotes: ["D","E","F#","G","A","B","C#"],
    keySignature: "D",
    explanation: "Ré majeur : D E F# G A B C#. Deux dièses nécessaires : F# (pour ½ ton E–F#... non, T) et C# (pour ½ ton B–C#... non, VII–VIII = ½ ton C#–D).",
    hint: "2 dièses : le 3e degré (F#) et le 7e degré (C#). Structure T–T–½T–T–T–T–½T depuis D.",
  },
  {
    id: "c1-build-scale-bb",
    type: "build",
    cours: 1, difficulty: 2,
    tags: ["gamme","Sib majeur","2 bémols"],
    concepts: ["gamme majeure","2 bémols"],
    question: "Construis la gamme de Sib majeur",
    correctNotes: ["Bb","C","D","Eb","F","G","A"],
    keySignature: "Bb",
    explanation: "Sib majeur : Bb C D Eb F G A. 2 bémols : Bb (tonique) et Eb (IVe degré). La structure T–T–½T–T–T–T–½T est respectée.",
    hint: "Commence sur Bb. Le 4e degré doit être bémolisé (Eb) pour maintenir la structure.",
  },
];

// ════════════════════════════════════════════════════════════════════════════
// COURS 2 — Les accords : triades, tétrades, renversements
// ════════════════════════════════════════════════════════════════════════════

export const COURS2_IDENTIFY: IdentifyExercise[] = [
  // ── Types d'accords ──────────────────────────────────────────────────────
  {
    id: "c2-chord-c-major",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["triades","accord majeur","structure"],
    concepts: ["accord majeur","tierce majeure + tierce mineure"],
    question: "L'accord C majeur est constitué de :",
    context: "C – E – G",
    options: [
      { id:"a", label:"Tierce mineure + tierce majeure", isCorrect: false },
      { id:"b", label:"Tierce majeure + tierce mineure", isCorrect: true  },
      { id:"c", label:"Deux tierces majeures",           isCorrect: false },
      { id:"d", label:"Deux tierces mineures",           isCorrect: false },
    ],
    explanation: "C–E = tierce majeure (4 dt), E–G = tierce mineure (3 dt). Toute triade majeure = tierce M + tierce m.",
  },
  {
    id: "c2-chord-identify-am",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["triades","accord mineur","identification"],
    concepts: ["accord mineur","reconnaissance"],
    question: "Quel accord est formé par A – C – E ?",
    context: "A → C → E",
    options: [
      { id:"a", label:"A majeur",  isCorrect: false },
      { id:"b", label:"A mineur",  isCorrect: true  },
      { id:"c", label:"C majeur",  isCorrect: false },
      { id:"d", label:"F majeur",  isCorrect: false },
    ],
    explanation: "A–C = 3 demi-tons (tierce mineure), C–E = 4 demi-tons (tierce majeure) → Am. Tierce m + tierce M = accord mineur.",
  },
  {
    id: "c2-chord-identify-bdim",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["triades","accord diminué","identification"],
    concepts: ["accord diminué","deux tierces mineures"],
    question: "Quel accord est formé par B – D – F ?",
    context: "B → D → F",
    options: [
      { id:"a", label:"B mineur",   isCorrect: false },
      { id:"b", label:"D majeur",   isCorrect: false },
      { id:"c", label:"B diminué",  isCorrect: true  },
      { id:"d", label:"F majeur",   isCorrect: false },
    ],
    explanation: "B–D = 3 demi-tons (tierce min), D–F = 3 demi-tons (tierce min) → Bdim. Deux tierces mineures = accord diminué.",
  },
  {
    id: "c2-chord-identify-g7",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["tétrades","accord dominant7","G7"],
    concepts: ["accord de dominante 7","structure","triton"],
    question: "Quelles notes composent G7 ?",
    options: [
      { id:"a", label:"G – B – D – F#", isCorrect: false },
      { id:"b", label:"G – B – D – F",  isCorrect: true  },
      { id:"c", label:"G – Bb – D – F", isCorrect: false },
      { id:"d", label:"G – B – Db – F", isCorrect: false },
    ],
    explanation: "G7 = G–B–D–F. Triade G majeur (G–B–D) + septième mineure (F). Le triton B–F est à l'intérieur de cet accord.",
  },
  {
    id: "c2-chord-identify-cmaj7",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["tétrades","CMaj7","septième majeure"],
    concepts: ["accord majeur 7","Maj7"],
    question: "Quelles notes composent CMaj7 ?",
    options: [
      { id:"a", label:"C – E – G – Bb", isCorrect: false },
      { id:"b", label:"C – E – G – B",  isCorrect: true  },
      { id:"c", label:"C – Eb – G – B", isCorrect: false },
      { id:"d", label:"C – E – Gb – B", isCorrect: false },
    ],
    explanation: "CMaj7 = C–E–G–B. Triade C majeur (C–E–G) + septième majeure (B). À distinguer de C7 qui a Bb (7e mineure).",
  },
  {
    id: "c2-chord-identify-dm7",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["tétrades","Dm7","identification"],
    concepts: ["accord mineur 7","m7"],
    question: "Quelles notes composent Dm7 ?",
    options: [
      { id:"a", label:"D – F – A – C",  isCorrect: true  },
      { id:"b", label:"D – F# – A – C", isCorrect: false },
      { id:"c", label:"D – F – Ab – C", isCorrect: false },
      { id:"d", label:"D – F – A – B",  isCorrect: false },
    ],
    explanation: "Dm7 = D–F–A–C. Triade D mineur (D–F–A) + septième mineure (C). C'est le IIe degré de Do majeur.",
  },
  {
    id: "c2-chord-identify-bm7b5",
    type: "identify",
    cours: 2, difficulty: 2,
    tags: ["tétrades","Bm7b5","demi-diminué"],
    concepts: ["accord demi-diminué","m7b5","VIIe degré majeur"],
    question: "Quelles notes composent Bm7♭5 (Si demi-diminué) ?",
    options: [
      { id:"a", label:"B – D – F – A",  isCorrect: true  },
      { id:"b", label:"B – D – F# – A", isCorrect: false },
      { id:"c", label:"B – D – F – Ab", isCorrect: false },
      { id:"d", label:"B – Db – F – A", isCorrect: false },
    ],
    explanation: "Bm7♭5 = B–D–F–A. Triade Bdim (B–D–F, quinte diminuée) + septième mineure (A). C'est le VIIe degré de Do majeur.",
  },
  // ── Renversements ─────────────────────────────────────────────────────────
  {
    id: "c2-inversion-c-e",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["renversements","1er renversement","basse"],
    concepts: ["renversements","note à la basse"],
    question: "C/E est :",
    options: [
      { id:"a", label:"C majeur à l'état fondamental",   isCorrect: false },
      { id:"b", label:"C majeur en 1er renversement (E à la basse)", isCorrect: true },
      { id:"c", label:"C majeur en 2e renversement",     isCorrect: false },
      { id:"d", label:"E mineur",                        isCorrect: false },
    ],
    explanation: "C/E = accord de Do majeur avec Mi à la basse. Mi est la tierce de C → 1er renversement.",
  },
  {
    id: "c2-inversion-c-g",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["renversements","2e renversement"],
    concepts: ["renversements","quinte à la basse"],
    question: "C/G est :",
    options: [
      { id:"a", label:"C majeur à l'état fondamental",   isCorrect: false },
      { id:"b", label:"C majeur en 1er renversement",    isCorrect: false },
      { id:"c", label:"C majeur en 2e renversement (G à la basse)", isCorrect: true },
      { id:"d", label:"G majeur",                        isCorrect: false },
    ],
    explanation: "C/G = accord de Do majeur avec Sol à la basse. Sol est la quinte de C → 2e renversement.",
  },
  {
    id: "c2-chord-scale-1",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["accords","gamme majeure","degrés"],
    concepts: ["harmonisation de la gamme","IIe degré"],
    question: "En Do majeur, quel accord produit le IIe degré ?",
    context: "Gamme de Do majeur : C – D – E – F – G – A – B",
    options: [
      { id:"a", label:"C majeur",  isCorrect: false },
      { id:"b", label:"D mineur",  isCorrect: true  },
      { id:"c", label:"D majeur",  isCorrect: false },
      { id:"d", label:"E mineur",  isCorrect: false },
    ],
    explanation: "D(II)–F(IV)–A(VI) en Do majeur. D–F = tierce mineure (3 dt), F–A = tierce majeure (4 dt) → Dm.",
  },
  {
    id: "c2-chord-scale-dominant",
    type: "identify",
    cours: 2, difficulty: 1,
    tags: ["accords","gamme majeure","Ve degré","G7"],
    concepts: ["accord de dominante","Ve degré majeur"],
    question: "En Do majeur, quel accord de 7e produit le Ve degré ?",
    options: [
      { id:"a", label:"GMaj7",  isCorrect: false },
      { id:"b", label:"Gm7",    isCorrect: false },
      { id:"c", label:"G7",     isCorrect: true  },
      { id:"d", label:"Gdim7",  isCorrect: false },
    ],
    explanation: "G(V)–B(VII)–D(II)–F(IV). G–B = tierce majeure, B–D = tierce mineure → G majeur. D–F = tierce mineure (7e mineure) → G7. Le seul accord de dominante 7 dans la gamme.",
  },
  {
    id: "c2-chord-double-on-4v",
    type: "identify",
    cours: 2, difficulty: 2,
    tags: ["doublures","4 voix","fondamentale"],
    concepts: ["doublure","écriture à 4 voix"],
    question: "Dans une triade à l'état fondamental répartie sur 4 voix, quelle note doit-on doubler par défaut ?",
    options: [
      { id:"a", label:"La tierce",       isCorrect: false },
      { id:"b", label:"La quinte",       isCorrect: false },
      { id:"c", label:"La fondamentale", isCorrect: true  },
      { id:"d", label:"La septième",     isCorrect: false },
    ],
    explanation: "On double la fondamentale par défaut — c'est la note la plus stable. Exception : au VIIe degré, on double la tierce (jamais la sensible).",
  },
  {
    id: "c2-chord-quality-sequence",
    type: "identify",
    cours: 2, difficulty: 2,
    tags: ["gamme majeure","séquence","qualités"],
    concepts: ["harmonisation de la gamme","séquence d'accords"],
    question: "En gamme majeure, la séquence des qualités d'accords à 7e est :",
    options: [
      { id:"a", label:"Maj7 – m7 – m7 – Maj7 – 7 – m7 – m7♭5", isCorrect: true  },
      { id:"b", label:"7 – m7 – m7 – Maj7 – Maj7 – m7 – m7♭5", isCorrect: false },
      { id:"c", label:"Maj7 – m7 – Maj7 – m7 – 7 – m7 – dim7",  isCorrect: false },
      { id:"d", label:"Maj7 – m7 – m7 – 7 – Maj7 – m7 – m7♭5", isCorrect: false },
    ],
    explanation: "I=Maj7, II=m7, III=m7, IV=Maj7, V=7, VI=m7, VII=m7♭5. Cette séquence est invariable dans toutes les tonalités majeures.",
  },
];

// ─── Exercices de construction — cours 2 ─────────────────────────────────────

export const COURS2_BUILD: BuildExercise[] = [
  {
    id: "c2-build-c-major-triad",
    type: "build",
    cours: 2, difficulty: 1,
    tags: ["triades","C major","construction"],
    concepts: ["accord majeur","tierce majeure","quinte juste"],
    question: "Construis la triade de Do majeur (3 notes)",
    correctNotes: ["C","E","G"],
    keySignature: "C",
    explanation: "C majeur = C–E–G. C–E = tierce majeure (4 dt), E–G = tierce mineure (3 dt), C–G = quinte juste (7 dt).",
    hint: "Triade majeure = fondamentale + tierce majeure (4 dt) + quinte juste (7 dt depuis la fondamentale).",
  },
  {
    id: "c2-build-dm-triad",
    type: "build",
    cours: 2, difficulty: 1,
    tags: ["triades","D mineur","construction"],
    concepts: ["accord mineur","tierce mineure","quinte juste"],
    question: "Construis la triade de Ré mineur (3 notes)",
    correctNotes: ["D","F","A"],
    explanation: "Dm = D–F–A. D–F = tierce mineure (3 dt), F–A = tierce majeure (4 dt), D–A = quinte juste (7 dt).",
    hint: "Triade mineure = fondamentale + tierce mineure (3 dt) + quinte juste.",
  },
  {
    id: "c2-build-g7-tetrad",
    type: "build",
    cours: 2, difficulty: 1,
    tags: ["tétrades","G7","construction"],
    concepts: ["accord dominant 7","triton","sensible"],
    question: "Construis l'accord G7 (4 notes)",
    correctNotes: ["G","B","D","F"],
    explanation: "G7 = G–B–D–F. Triade G majeur (G–B–D) + septième mineure F (10 dt depuis G). Le triton B–F est à l'intérieur.",
    hint: "G7 = triade G majeur + septième mineure. La 7e est à 10 demi-tons de la fondamentale.",
  },
  {
    id: "c2-build-cmaj7-tetrad",
    type: "build",
    cours: 2, difficulty: 1,
    tags: ["tétrades","CMaj7","septième majeure"],
    concepts: ["accord Maj7","septième majeure"],
    question: "Construis l'accord CMaj7 (4 notes)",
    correctNotes: ["C","E","G","B"],
    explanation: "CMaj7 = C–E–G–B. Triade C majeur + septième majeure B (11 dt depuis C). À distinguer de C7 (avec Bb).",
    hint: "Maj7 = triade majeure + septième MAJEURE (11 demi-tons depuis la fondamentale).",
  },
  {
    id: "c2-build-am7-tetrad",
    type: "build",
    cours: 2, difficulty: 1,
    tags: ["tétrades","Am7","mineur 7"],
    concepts: ["accord mineur 7","m7"],
    question: "Construis l'accord Am7 (4 notes)",
    correctNotes: ["A","C","E","G"],
    explanation: "Am7 = A–C–E–G. Triade A mineur (A–C–E) + septième mineure G (10 dt depuis A). C'est le VIe degré de Do majeur.",
    hint: "m7 = triade mineure + septième mineure (10 demi-tons depuis la fondamentale).",
  },
  {
    id: "c2-build-e-major-triad",
    type: "build",
    cours: 2, difficulty: 2,
    tags: ["triades","Mi majeur","dièses"],
    concepts: ["accord majeur","altérations"],
    question: "Construis la triade de Mi majeur (3 notes)",
    correctNotes: ["E","G#","B"],
    explanation: "E majeur = E–G#–B. E–G# = tierce majeure (4 dt), G#–B = tierce mineure (3 dt). G# est nécessaire pour la tierce majeure.",
    hint: "La tierce d'E majeur est G# (et non G naturel qui ferait une tierce mineure).",
  },
  {
    id: "c2-build-bb-major-triad",
    type: "build",
    cours: 2, difficulty: 2,
    tags: ["triades","Sib majeur","bémols"],
    concepts: ["accord majeur","altérations bémols"],
    question: "Construis la triade de Sib majeur (3 notes)",
    correctNotes: ["Bb","D","F"],
    explanation: "Bb majeur = Bb–D–F. Bb–D = tierce majeure (4 dt), D–F = tierce mineure (3 dt), Bb–F = quinte juste (7 dt).",
    hint: "La fondamentale est Bb (Sib). Applique tierce majeure + quinte juste.",
  },
  {
    id: "c2-build-c-major-all-degrees",
    type: "build",
    cours: 2, difficulty: 2,
    tags: ["gamme","Do majeur","tous les accords"],
    concepts: ["harmonisation complète","7 accords diatoniques"],
    question: "Quelles sont les fondamentales des 7 accords diatoniques de Do majeur ?",
    correctNotes: ["C","D","E","F","G","A","B"],
    keySignature: "C",
    explanation: "Les 7 degrés de Do majeur : C(I) D(II) E(III) F(IV) G(V) A(VI) B(VII). Chaque note de la gamme est la fondamentale d'un accord.",
    hint: "Ce sont simplement les 7 notes de la gamme de Do majeur.",
  },
];

// ─── Export ────────────────────────────────────────────────────────────────────

export const COURS1_EXERCISES = [...COURS1_IDENTIFY, ...COURS1_BUILD];
export const COURS2_EXERCISES = [...COURS2_IDENTIFY, ...COURS2_BUILD];