/**
 * translate-cours36.js
 * Adds narrative translation keys for Cours36 to all 6 language JSON files.
 * Run: node scripts/translate-cours36.js
 */

const fs = require('fs');

const NARRATIVE = {
  fr: {
    maitreCardConcept: "Harmonie statique et impressionnisme précurseur",
    maitreCardAnecdote: "Satie a inventé la 'musique d'ameublement' (1920) — une musique censée se confondre avec le bruit de l'environnement, comme un meuble sonore. Lors de sa première exécution, le public s'assit poliment et écouta. Satie furieux parcourait la salle en criant : 'Parlez ! Bougez ! N'écoutez pas !' Il préfigurait Brian Eno et la musique ambient de 50 ans.",
    maitreCardLesson: "La musique peut exister sans tension ni résolution — la couleur harmonique est une fin en soi.",

    // Section Debussy
    debussyH2: "L'harmonie impressionniste de Debussy",
    debussyP: "Debussy a dissous le système tonal classique non pas en le rejetant, mais en le contournant. Il a remplacé les fonctions harmoniques (T/SD/D) par des couleurs sonores — l'accord n'a plus de rôle, il a une texture. La tension-résolution cède la place à l'atmosphère.",
    debussyInfoBox: "<strong>Principe fondamental :</strong> Chez Debussy, la progression harmonique suit la mélodie et l'image sonore — pas la logique fonctionnelle. Analyser Debussy avec les fonctions T/SD/D revient à appliquer les règles de l'échecs aux dés. La grille d'analyse est inappropriée.",
    debussyH3Techniques: "5 techniques harmoniques caractéristiques",
    debussyH3Analyser: "Comment analyser une pièce impressionniste",
    debussyWarnBox: "<strong>Erreur classique :</strong> Chercher des cadences V→I dans Debussy. Debussy les évite systématiquement — c'est le principe même de son esthétique. Le Prélude à l'après-midi d'un faune (110 mesures) ne contient aucune cadence dominante-tonique classique. L'harmonie \"flotte\" sans jamais se résoudre.",

    // Techniques Debussy
    tech_d0_nom: "Gamme par tons",
    tech_d0_principe: "6 tons entiers sans demi-ton — Do–Ré–Mi–Fa#–Sol#–La#",
    tech_d0_effet: "Flottement total : sans sensible, aucune note ne tire vers la suivante. Tous les accords sont augmentés.",
    tech_d1_nom: "Gamme octatonique (ton-demi-ton)",
    tech_d1_principe: "8 notes alternant ton et demi-ton — Do–Ré–Mib–Fa–Fa#–Sol#–La–Si",
    tech_d1_effet: "Couleur ambiguë et symétrique — la tonalité est impossible à établir (la gamme se répète à distance de tierce mineure).",
    tech_d2_nom: "Planing (homorythmie parallèle)",
    tech_d2_principe: "Toutes les voix bougent au même rythme avec le même type d'accord transposé",
    tech_d2_effet: "L'accord se déplace comme un bloc sonore — les quintes parallèles sont intentionnelles, créant l'effet de glissement caractéristique.",
    tech_d3_nom: "Pédale longue",
    tech_d3_principe: "Basse immobile (note tenue) pendant que l'harmonie change librement au-dessus",
    tech_d3_effet: "Suspension temporelle — le temps harmonique s'arrête à la basse. Technique médiévale (organum) réinventée.",
    tech_d4_nom: "Quintes ouvertes médiévales",
    tech_d4_principe: "Accord de fondamentale + quinte sans tierce — ni majeur ni mineur",
    tech_d4_effet: "Pureté archaïque et atemporelle, évocation du plain-chant et des cloches (La Cathédrale Engloutie).",

    // Étapes d'analyse
    step1_label: "Identifier la gamme source",
    step1_desc: "Par tons (6 tons entiers), octatonique (ton-demi-ton), pentatonique, ou mode ecclésiastique ?",
    step2_label: "Repérer la technique de texture",
    step2_desc: "Planing ? Pédale longue ? Quintes ouvertes ? Homorythmie parallèle ?",
    step3_label: "Analyser la couleur de l'accord",
    step3_desc: "Qualité de l'accord, extensions présentes, registre. Pas de fonction harmonique.",
    step4_label: "Observer registre et dynamique",
    step4_desc: "Les changements de couleur viennent souvent du registre et du volume, pas de la progression d'accords.",

    // Section Ravel
    ravelH2: "L'harmonie calculée de Ravel",
    ravelP: "Ravel partage avec Debussy la surface impressionniste — accords colorés, extensions, modes — mais sa logique est opposée. Ravel se définissait lui-même comme un \"horloger\" : chaque accord est calculé, chaque voicing mesuré. La Pavane, le Boléro, les Valses nobles sont des constructions architecturales déguisées en rêveries.",
    ravelInfoBox: "<strong>Différence essentielle :</strong> Debussy crée intuitivement par images et couleurs sonores. Ravel calcule avec une rigueur quasi mathématique. Même surface impressionniste, logiques compositionnelles opposées. Debussy lui-même les distinguait clairement et refusait d'être associé à Ravel.",
    ravelH3Techniques: "5 techniques harmoniques de Ravel",
    ravelH3Satie: "Satie : le précurseur oublié",

    // Techniques Ravel
    tech_r0_nom: "Polyaccord (superposition)",
    tech_r0_principe: "Deux accords complets superposés — Do Maj + Ré Maj = cluster hybride",
    tech_r0_effet: "Couleur harmonique dense et inédite — les deux accords restent reconnaissables mais créent quelque chose de nouveau.",
    tech_r1_nom: "Note ajoutée (6te ou 9e)",
    tech_r1_principe: "Enrichissement de l'accord sans 7te — CMaj6 : Do–Mi–Sol–La",
    tech_r1_effet: "Douceur lumineuse — moins 'jazz' que le Maj7, plus 'naïf' et tendre. Signature du style ravélien.",
    tech_r2_nom: "Add9 (9e sans 7te)",
    tech_r2_principe: "Accord majeur + 9e : Do–Mi–Sol–Ré — 9e sans 7te intermédiaire",
    tech_r2_effet: "Ouverture et clarté — l'accord semble aspirer vers le haut. Très différent du Maj9 (qui ajoute aussi la 7te).",
    tech_r3_nom: "Modalité néoclassique",
    tech_r3_principe: "Modes anciens (dorien, phrygien, lydien) dans un langage moderne",
    tech_r3_effet: "Couleur modale sans archaïsme — le mode dorien sur Sol donne une lumière particulière absente du mineur harmonique.",
    tech_r4_nom: "Ostinato harmonique (Boléro)",
    tech_r4_principe: "Un seul accord (Do7) pendant 15 minutes — la tension vient de l'orchestration progressive",
    tech_r4_effet: "Démonstration que la progression harmonique n'est pas le seul moteur de tension — le timbre et la dynamique suffisent.",

    // Satie box
    satieName: "Erik Satie (1866–1925)",
    satieP: "Satie précède Debussy et Ravel et préfigure le minimalisme de 50 ans. Ses <strong>Gymnopédies</strong> (1888) utilisent des accords de 7e majeure en balancement lent — deux couleurs qui alternent sans jamais progresser dramatiquement. Ses <strong>Vexations</strong> (1893, découvertes après sa mort) anticipent Steve Reich : une pièce de 52 secondes à jouer 840 fois d'affilée.",
    satieAccord1Label: "Gymnopédie n°1 — accord I (Ré Maj7)",
    satieAccord1Btn: "▶ Accord I (Dmaj7)",
    satieAccord2Label: "Accord IV (Sol Maj7)",
    satieAccord2Btn: "▶ Accord IV (Gmaj7)",

    ravelWarnBox: "<strong>Erreur fréquente :</strong> Croire que Debussy et Ravel sont le même compositeur avec le même style. Leur surface est similaire (impressionnisme, couleurs) mais leur méthode est opposée. Ravel peut écrire en formes classiques strictes (Sonatine pour piano, Quatuor à cordes) avec un langage impressionniste. Debussy évite les formes classiques. Cette différence est fondamentale.",

    // Quiz
    quizH2: "Quiz — Impressionnisme : Debussy, Ravel, Satie",
    ecouter: "▶ Écouter",
  },

  en: {
    maitreCardConcept: "Static harmony and precursor impressionism",
    maitreCardAnecdote: "Satie invented 'furniture music' (1920) — music meant to blend with ambient noise, like a sonic piece of furniture. At its premiere, the audience politely sat and listened. An outraged Satie stormed through the hall shouting: 'Talk! Move! Don't listen!' He prefigured Brian Eno and ambient music by 50 years.",
    maitreCardLesson: "Music can exist without tension or resolution — harmonic colour is an end in itself.",

    debussyH2: "Debussy's impressionist harmony",
    debussyP: "Debussy dissolved the classical tonal system not by rejecting it, but by circumventing it. He replaced harmonic functions (T/SD/D) with sound colours — a chord no longer has a role, it has a texture. Tension-resolution gives way to atmosphere.",
    debussyInfoBox: "<strong>Fundamental principle:</strong> In Debussy, harmonic progression follows the melody and the sonic image — not functional logic. Analysing Debussy using T/SD/D functions is like applying chess rules to dice. The analytical framework is inappropriate.",
    debussyH3Techniques: "5 characteristic harmonic techniques",
    debussyH3Analyser: "How to analyse an impressionist piece",
    debussyWarnBox: "<strong>Classic mistake:</strong> Looking for V→I cadences in Debussy. Debussy systematically avoids them — it is the very principle of his aesthetic. The Prelude to the Afternoon of a Faun (110 bars) contains no classical dominant-tonic cadence. The harmony 'floats' without ever resolving.",

    tech_d0_nom: "Whole-tone scale",
    tech_d0_principe: "6 whole tones with no semitone — C–D–E–F#–G#–A#",
    tech_d0_effet: "Total floating: without a leading tone, no note pulls toward the next. All chords are augmented.",
    tech_d1_nom: "Octatonic scale (tone-semitone)",
    tech_d1_principe: "8 notes alternating tone and semitone — C–D–Eb–F–F#–Ab–A–B",
    tech_d1_effet: "Ambiguous, symmetrical colour — tonality is impossible to establish (the scale repeats at a minor third).",
    tech_d2_nom: "Planing (parallel homorhythm)",
    tech_d2_principe: "All voices move in the same rhythm with the same chord type transposed",
    tech_d2_effet: "The chord moves as a sound block — parallel fifths are intentional, creating the characteristic sliding effect.",
    tech_d3_nom: "Long pedal point",
    tech_d3_principe: "Stationary bass (held note) while the harmony changes freely above",
    tech_d3_effet: "Temporal suspension — harmonic time stops in the bass. Medieval technique (organum) reinvented.",
    tech_d4_nom: "Medieval open fifths",
    tech_d4_principe: "Root + fifth chord with no third — neither major nor minor",
    tech_d4_effet: "Archaic, timeless purity, evoking plainchant and bells (La Cathédrale Engloutie).",

    step1_label: "Identify the source scale",
    step1_desc: "Whole-tone (6 whole tones), octatonic (tone-semitone), pentatonic, or church mode?",
    step2_label: "Spot the texture technique",
    step2_desc: "Planing? Pedal point? Open fifths? Parallel homorhythm?",
    step3_label: "Analyse chord colour",
    step3_desc: "Chord quality, extensions present, register. No harmonic function.",
    step4_label: "Observe register and dynamics",
    step4_desc: "Colour changes often come from register and volume, not chord progressions.",

    ravelH2: "Ravel's calculated harmony",
    ravelP: "Ravel shares with Debussy the impressionist surface — coloured chords, extensions, modes — but his logic is the opposite. Ravel described himself as a 'watchmaker': every chord is calculated, every voicing measured. The Pavane, the Bolero, the Valses nobles are architectural constructions disguised as reveries.",
    ravelInfoBox: "<strong>Essential difference:</strong> Debussy creates intuitively through images and sonic colours. Ravel calculates with near-mathematical rigour. Same impressionist surface, opposite compositional logics. Debussy himself clearly distinguished between them and refused to be associated with Ravel.",
    ravelH3Techniques: "5 harmonic techniques of Ravel",
    ravelH3Satie: "Satie: the forgotten precursor",

    tech_r0_nom: "Polychord (superposition)",
    tech_r0_principe: "Two complete chords stacked — C Maj + D Maj = hybrid cluster",
    tech_r0_effet: "Dense, unprecedented harmonic colour — both chords remain recognisable but create something new.",
    tech_r1_nom: "Added note (6th or 9th)",
    tech_r1_principe: "Chord enrichment without 7th — CMaj6: C–E–G–A",
    tech_r1_effet: "Luminous softness — less 'jazzy' than Maj7, more 'naive' and tender. Signature of Ravel's style.",
    tech_r2_nom: "Add9 (9th without 7th)",
    tech_r2_principe: "Major chord + 9th: C–E–G–D — 9th without intermediate 7th",
    tech_r2_effet: "Openness and clarity — the chord seems to aspire upward. Very different from Maj9 (which also adds the 7th).",
    tech_r3_nom: "Neoclassical modality",
    tech_r3_principe: "Ancient modes (Dorian, Phrygian, Lydian) in a modern language",
    tech_r3_effet: "Modal colour without archaism — the Dorian mode on G gives a particular light absent from harmonic minor.",
    tech_r4_nom: "Harmonic ostinato (Bolero)",
    tech_r4_principe: "A single chord (C7) for 15 minutes — tension comes from progressive orchestration",
    tech_r4_effet: "Demonstration that harmonic progression is not the only driver of tension — timbre and dynamics suffice.",

    satieName: "Erik Satie (1866–1925)",
    satieP: "Satie precedes Debussy and Ravel and prefigures minimalism by 50 years. His <strong>Gymnopédies</strong> (1888) use major 7th chords in slow oscillation — two colours alternating without ever progressing dramatically. His <strong>Vexations</strong> (1893, discovered after his death) anticipate Steve Reich: a 52-second piece to be played 840 times in a row.",
    satieAccord1Label: "Gymnopédie No.1 — chord I (D Maj7)",
    satieAccord1Btn: "▶ Chord I (Dmaj7)",
    satieAccord2Label: "Chord IV (G Maj7)",
    satieAccord2Btn: "▶ Chord IV (Gmaj7)",

    ravelWarnBox: "<strong>Common mistake:</strong> Believing Debussy and Ravel are the same composer with the same style. Their surfaces are similar (impressionism, colours) but their methods are opposite. Ravel can write in strict classical forms (Piano Sonatine, String Quartet) with an impressionist language. Debussy avoids classical forms. This difference is fundamental.",

    quizH2: "Quiz — Impressionism: Debussy, Ravel, Satie",
    ecouter: "▶ Listen",
  },

  de: {
    maitreCardConcept: "Statische Harmonie und impressionistischer Vorläufer",
    maitreCardAnecdote: "Satie erfand die &bdquo;Möbelmusik&ldquo; (1920) — Musik, die im Umgebungsgeräusch aufgehen sollte wie ein klingendes Möbelstück. Bei der Uraufführung setzte sich das Publikum artig hin und hörte zu. Der wütende Satie durchstreifte den Saal und rief: &bdquo;Reden Sie! Bewegen Sie sich! Hören Sie nicht zu!&ldquo; Er nahm Brian Eno und die Ambient-Musik um 50 Jahre vorweg.",
    maitreCardLesson: "Musik kann ohne Spannung und Auflösung existieren — die Klangfarbe ist Selbstzweck.",

    debussyH2: "Debussys impressionistische Harmonie",
    debussyP: "Debussy löste das klassische Tonsystem nicht auf, indem er es ablehnte, sondern indem er es umging. Er ersetzte die harmonischen Funktionen (T/SD/D) durch Klangfarben — ein Akkord hat keine Funktion mehr, er hat eine Textur. Spannung-Auflösung weicht der Atmosphäre.",
    debussyInfoBox: "<strong>Grundprinzip:</strong> Bei Debussy folgt die harmonische Progression der Melodie und dem Klangbild — nicht der funktionalen Logik. Debussy mit T/SD/D-Funktionen zu analysieren ist, als würde man Schachregeln auf Würfelspiele anwenden. Das Analyseraster ist ungeeignet.",
    debussyH3Techniques: "5 charakteristische Harmonie-Techniken",
    debussyH3Analyser: "Wie man ein impressionistisches Stück analysiert",
    debussyWarnBox: "<strong>Klassischer Fehler:</strong> V→I-Kadenzen bei Debussy suchen. Debussy vermeidet sie systematisch — das ist das Kernprinzip seiner Ästhetik. Das Prélude à l'après-midi d'un faune (110 Takte) enthält keine klassische Dominante-Tonika-Kadenz. Die Harmonie &bdquo;schwebt&ldquo;, ohne sich je aufzulösen.",

    tech_d0_nom: "Ganztonleiter",
    tech_d0_principe: "6 Ganztöne ohne Halbton — C–D–E–Fis–Gis–Ais",
    tech_d0_effet: "Totales Schweben: Ohne Leitton zieht keine Note zur nächsten. Alle Akkorde sind übermäßig.",
    tech_d1_nom: "Oktatonische Leiter (Ton-Halbton)",
    tech_d1_principe: "8 Töne im Wechsel von Ganz- und Halbton — C–D–Es–F–Fis–Gis–A–H",
    tech_d1_effet: "Mehrdeutige, symmetrische Farbe — Tonalität ist unmöglich festzustellen (die Leiter wiederholt sich in kleiner Terz).",
    tech_d2_nom: "Planing (parallele Homorhythmik)",
    tech_d2_principe: "Alle Stimmen bewegen sich im gleichen Rhythmus mit dem gleichen transponierenden Akkordtyp",
    tech_d2_effet: "Der Akkord bewegt sich als Klangblock — Quintparallelen sind beabsichtigt und erzeugen den charakteristischen Gleiteffekt.",
    tech_d3_nom: "Langer Orgelpunkt",
    tech_d3_principe: "Ruhende Bassnote, während die Harmonie darüber frei wechselt",
    tech_d3_effet: "Zeitliche Suspension — die harmonische Zeit steht im Bass still. Mittelalterliche Technik (Organum) neu erfunden.",
    tech_d4_nom: "Mittelalterliche offene Quinten",
    tech_d4_principe: "Akkord aus Grundton + Quinte ohne Terz — weder Dur noch Moll",
    tech_d4_effet: "Archaische, zeitlose Reinheit — Evokation von Gregorianik und Glocken (La Cathédrale Engloutie).",

    step1_label: "Quelltonleiter identifizieren",
    step1_desc: "Ganzton (6 Ganztöne), oktatonisch (Ton-Halbton), pentatonisch oder Kirchenmodus?",
    step2_label: "Textur-Technik erkennen",
    step2_desc: "Planing? Orgelpunkt? Offene Quinten? Parallele Homorhythmik?",
    step3_label: "Akkordfarbe analysieren",
    step3_desc: "Akkordqualität, vorhandene Erweiterungen, Register. Keine harmonische Funktion.",
    step4_label: "Register und Dynamik beobachten",
    step4_desc: "Farbwechsel kommen oft aus Register und Lautstärke, nicht aus der Akkordfolge.",

    ravelH2: "Ravels berechnete Harmonie",
    ravelP: "Ravel teilt mit Debussy die impressionistische Oberfläche — farbige Akkorde, Erweiterungen, Modi — doch seine Logik ist entgegengesetzt. Ravel bezeichnete sich selbst als &bdquo;Uhrmacher&ldquo;: Jeder Akkord ist berechnet, jedes Voicing abgewogen. Die Pavane, der Bolero, die Valses nobles sind architektonische Konstruktionen, als Träumereien verkleidet.",
    ravelInfoBox: "<strong>Wesentlicher Unterschied:</strong> Debussy schafft intuitiv durch Bilder und Klangfarben. Ravel rechnet mit nahezu mathematischer Strenge. Gleiche impressionistische Oberfläche, entgegengesetzte kompositorische Logik. Debussy selbst unterschied klar zwischen beiden und weigerte sich, mit Ravel in Verbindung gebracht zu werden.",
    ravelH3Techniques: "5 harmonische Techniken Ravels",
    ravelH3Satie: "Satie: der vergessene Vorläufer",

    tech_r0_nom: "Polyakkord (Überlagerung)",
    tech_r0_principe: "Zwei vollständige Akkorde übereinander — C-Dur + D-Dur = hybrider Cluster",
    tech_r0_effet: "Dichte, neuartige Klangfarbe — beide Akkorde bleiben erkennbar, schaffen aber etwas Neues.",
    tech_r1_nom: "Hinzugefügte Note (6te oder 9e)",
    tech_r1_principe: "Akkorderweiterung ohne Septime — CMaj6: C–E–G–A",
    tech_r1_effet: "Leuchtende Sanftheit — weniger &bdquo;jazzig&ldquo; als Maj7, &bdquo;naiver&ldquo; und zarter. Signatur des Ravelschen Stils.",
    tech_r2_nom: "Add9 (None ohne Septime)",
    tech_r2_principe: "Durakkord + None: C–E–G–D — None ohne vermittelnde Septime",
    tech_r2_effet: "Offenheit und Klarheit — der Akkord scheint nach oben zu streben. Sehr verschieden von Maj9 (das auch die Septime hinzufügt).",
    tech_r3_nom: "Neoklassische Modalität",
    tech_r3_principe: "Alte Modi (Dorisch, Phrygisch, Lydisch) in moderner Sprache",
    tech_r3_effet: "Modale Farbe ohne Archaismus — der dorische Modus auf G erzeugt ein besonderes Licht, das der harmonischen Molltonart fehlt.",
    tech_r4_nom: "Harmonisches Ostinato (Bolero)",
    tech_r4_principe: "Ein einziger Akkord (C7) für 15 Minuten — die Spannung kommt aus der progressiven Orchestrierung",
    tech_r4_effet: "Beweis, dass Akkordfolge nicht der einzige Spannungsmotor ist — Klangfarbe und Dynamik genügen.",

    satieName: "Erik Satie (1866–1925)",
    satieP: "Satie geht Debussy und Ravel voraus und nimmt den Minimalismus um 50 Jahre vorweg. Seine <strong>Gymnopédies</strong> (1888) verwenden Dur-Septakkorde in langsamer Schaukel — zwei Farben, die wechseln, ohne je dramatisch fortzuschreiten. Seine <strong>Vexations</strong> (1893, nach seinem Tod entdeckt) antizipieren Steve Reich: ein 52-sekündiges Stück, das 840 Mal hintereinander gespielt werden soll.",
    satieAccord1Label: "Gymnopédie Nr. 1 — Akkord I (D Maj7)",
    satieAccord1Btn: "▶ Akkord I (Dmaj7)",
    satieAccord2Label: "Akkord IV (G Maj7)",
    satieAccord2Btn: "▶ Akkord IV (Gmaj7)",

    ravelWarnBox: "<strong>Häufiger Fehler:</strong> Zu glauben, Debussy und Ravel seien derselbe Komponist mit demselben Stil. Ihre Oberfläche ist ähnlich (Impressionismus, Farben), ihre Methode jedoch entgegengesetzt. Ravel kann in strengen klassischen Formen (Sonatine für Klavier, Streichquartett) mit impressionistischer Sprache schreiben. Debussy meidet klassische Formen. Dieser Unterschied ist fundamental.",

    quizH2: "Quiz — Impressionismus: Debussy, Ravel, Satie",
    ecouter: "▶ Hören",
  },

  es: {
    maitreCardConcept: "Armonía estática e impresionismo precursor",
    maitreCardAnecdote: "Satie inventó la 'música de mobiliario' (1920) — una música destinada a confundirse con el ruido ambiental, como un mueble sonoro. En su primera ejecución, el público se sentó educadamente y escuchó. Satie, furioso, recorría la sala gritando: '¡Hablen! ¡Muévanse! ¡No escuchen!' Prefiguraba a Brian Eno y la música ambient en 50 años.",
    maitreCardLesson: "La música puede existir sin tensión ni resolución — el color armónico es un fin en sí mismo.",

    debussyH2: "La armonía impresionista de Debussy",
    debussyP: "Debussy disolvió el sistema tonal clásico no rechazándolo, sino rodeándolo. Reemplazó las funciones armónicas (T/SD/D) por colores sonoros — el acorde ya no tiene un papel, tiene una textura. La tensión-resolución cede paso a la atmósfera.",
    debussyInfoBox: "<strong>Principio fundamental:</strong> En Debussy, la progresión armónica sigue la melodía y la imagen sonora — no la lógica funcional. Analizar a Debussy con las funciones T/SD/D equivale a aplicar las reglas del ajedrez a los dados. La cuadrícula de análisis es inapropiada.",
    debussyH3Techniques: "5 técnicas armónicas características",
    debussyH3Analyser: "Cómo analizar una pieza impresionista",
    debussyWarnBox: "<strong>Error clásico:</strong> Buscar cadencias V→I en Debussy. Debussy las evita sistemáticamente — es el principio mismo de su estética. El Preludio a la siesta de un fauno (110 compases) no contiene ninguna cadencia dominante-tónica clásica. La armonía 'flota' sin resolverse nunca.",

    tech_d0_nom: "Escala de tonos enteros",
    tech_d0_principe: "6 tonos enteros sin semitono — Do–Re–Mi–Fa#–Sol#–La#",
    tech_d0_effet: "Flotación total: sin sensible, ninguna nota atrae a la siguiente. Todos los acordes son aumentados.",
    tech_d1_nom: "Escala octatónica (tono-semitono)",
    tech_d1_principe: "8 notas alternando tono y semitono — Do–Re–Mib–Fa–Fa#–Sol#–La–Si",
    tech_d1_effet: "Color ambiguo y simétrico — la tonalidad es imposible de establecer (la escala se repite a una tercera menor).",
    tech_d2_nom: "Planing (homorritmo paralelo)",
    tech_d2_principe: "Todas las voces se mueven al mismo ritmo con el mismo tipo de acorde transpuesto",
    tech_d2_effet: "El acorde se desplaza como un bloque sonoro — las quintas paralelas son intencionales, creando el característico efecto de deslizamiento.",
    tech_d3_nom: "Pedal larga",
    tech_d3_principe: "Bajo inmóvil (nota sostenida) mientras la armonía cambia libremente encima",
    tech_d3_effet: "Suspensión temporal — el tiempo armónico se detiene en el bajo. Técnica medieval (organum) reinventada.",
    tech_d4_nom: "Quintas abiertas medievales",
    tech_d4_principe: "Acorde de fundamental + quinta sin tercera — ni mayor ni menor",
    tech_d4_effet: "Pureza arcaica y atemporal, evocación del canto llano y las campanas (La Catedral Sumergida).",

    step1_label: "Identificar la escala fuente",
    step1_desc: "¿Por tonos (6 tonos enteros), octatónica (tono-semitono), pentatónica o modo eclesiástico?",
    step2_label: "Identificar la técnica de textura",
    step2_desc: "¿Planing? ¿Pedal larga? ¿Quintas abiertas? ¿Homorritmo paralelo?",
    step3_label: "Analizar el color del acorde",
    step3_desc: "Calidad del acorde, extensiones presentes, registro. Sin función armónica.",
    step4_label: "Observar registro y dinámica",
    step4_desc: "Los cambios de color suelen venir del registro y el volumen, no de la progresión de acordes.",

    ravelH2: "La armonía calculada de Ravel",
    ravelP: "Ravel comparte con Debussy la superficie impresionista — acordes coloridos, extensiones, modos — pero su lógica es opuesta. Ravel se definía a sí mismo como un 'relojero': cada acorde está calculado, cada voicing medido. La Pavana, el Bolero, los Valses nobles son construcciones arquitectónicas disfrazadas de ensoñaciones.",
    ravelInfoBox: "<strong>Diferencia esencial:</strong> Debussy crea intuitivamente mediante imágenes y colores sonoros. Ravel calcula con un rigor casi matemático. Misma superficie impresionista, lógicas compositivas opuestas. El propio Debussy los distinguía claramente y se negaba a ser asociado con Ravel.",
    ravelH3Techniques: "5 técnicas armónicas de Ravel",
    ravelH3Satie: "Satie: el precursor olvidado",

    tech_r0_nom: "Poliacorde (superposición)",
    tech_r0_principe: "Dos acordes completos superpuestos — Do Maj + Re Maj = cluster híbrido",
    tech_r0_effet: "Color armónico denso e inédito — ambos acordes siguen siendo reconocibles pero crean algo nuevo.",
    tech_r1_nom: "Nota añadida (6ª o 9ª)",
    tech_r1_principe: "Enriquecimiento del acorde sin 7ª — CMaj6: Do–Mi–Sol–La",
    tech_r1_effet: "Dulzura luminosa — menos 'jazz' que el Maj7, más 'ingenuo' y tierno. Sello del estilo raveliano.",
    tech_r2_nom: "Add9 (9ª sin 7ª)",
    tech_r2_principe: "Acorde mayor + 9ª: Do–Mi–Sol–Re — 9ª sin 7ª intermedia",
    tech_r2_effet: "Apertura y claridad — el acorde parece aspirar hacia arriba. Muy diferente del Maj9 (que también añade la 7ª).",
    tech_r3_nom: "Modalidad neoclásica",
    tech_r3_principe: "Modos antiguos (dórico, frigio, lidio) en un lenguaje moderno",
    tech_r3_effet: "Color modal sin arcaísmo — el modo dórico sobre Sol da una luz particular ausente del menor armónico.",
    tech_r4_nom: "Ostinato armónico (Bolero)",
    tech_r4_principe: "Un solo acorde (Do7) durante 15 minutos — la tensión viene de la orquestación progresiva",
    tech_r4_effet: "Demostración de que la progresión armónica no es el único motor de tensión — el timbre y la dinámica son suficientes.",

    satieName: "Erik Satie (1866–1925)",
    satieP: "Satie precede a Debussy y Ravel y prefigura el minimalismo en 50 años. Sus <strong>Gymnopédies</strong> (1888) utilizan acordes de 7ª mayor en balanceo lento — dos colores que alternan sin progresar dramáticamente. Sus <strong>Vexations</strong> (1893, descubiertas tras su muerte) anticipan a Steve Reich: una pieza de 52 segundos que debe tocarse 840 veces seguidas.",
    satieAccord1Label: "Gymnopédie n°1 — acorde I (Re Maj7)",
    satieAccord1Btn: "▶ Acorde I (Dmaj7)",
    satieAccord2Label: "Acorde IV (Sol Maj7)",
    satieAccord2Btn: "▶ Acorde IV (Gmaj7)",

    ravelWarnBox: "<strong>Error frecuente:</strong> Creer que Debussy y Ravel son el mismo compositor con el mismo estilo. Su superficie es similar (impresionismo, colores) pero su método es opuesto. Ravel puede escribir en formas clásicas estrictas (Sonatina para piano, Cuarteto de cuerdas) con un lenguaje impresionista. Debussy evita las formas clásicas. Esta diferencia es fundamental.",

    quizH2: "Quiz — Impresionismo: Debussy, Ravel, Satie",
    ecouter: "▶ Escuchar",
  },

  it: {
    maitreCardConcept: "Armonia statica e impressionismo precursore",
    maitreCardAnecdote: "Satie inventò la 'musica d'arredamento' (1920) — una musica destinata a confondersi con il rumore ambientale, come un mobile sonoro. Alla prima esecuzione, il pubblico si sedette educatamente e ascoltò. Satie, furioso, percorreva la sala gridando: 'Parlate! Muovetevi! Non ascoltate!' Anticipava Brian Eno e la musica ambient di 50 anni.",
    maitreCardLesson: "La musica può esistere senza tensione né risoluzione — il colore armonico è un fine in sé.",

    debussyH2: "L'armonia impressionista di Debussy",
    debussyP: "Debussy ha dissolto il sistema tonale classico non rifiutandolo, ma aggirándolo. Ha sostituito le funzioni armoniche (T/SD/D) con colori sonori — l'accordo non ha più un ruolo, ha una texture. La tensione-risoluzione cede il posto all'atmosfera.",
    debussyInfoBox: "<strong>Principio fondamentale:</strong> In Debussy la progressione armonica segue la melodia e l'immagine sonora — non la logica funzionale. Analizzare Debussy con le funzioni T/SD/D equivale ad applicare le regole degli scacchi ai dadi. La griglia analitica è inadeguata.",
    debussyH3Techniques: "5 tecniche armoniche caratteristiche",
    debussyH3Analyser: "Come analizzare un pezzo impressionista",
    debussyWarnBox: "<strong>Errore classico:</strong> Cercare cadenze V→I in Debussy. Debussy le evita sistematicamente — è il principio stesso della sua estetica. Il Prélude à l'après-midi d'un faune (110 battute) non contiene alcuna cadenza dominante-tonica classica. L'armonia 'fluttua' senza mai risolversi.",

    tech_d0_nom: "Scala per toni interi",
    tech_d0_principe: "6 toni interi senza semitono — Do–Re–Mi–Fa#–Sol#–La#",
    tech_d0_effet: "Fluttuazione totale: senza sensibile, nessuna nota attira la successiva. Tutti gli accordi sono aumentati.",
    tech_d1_nom: "Scala ottatonica (tono-semitono)",
    tech_d1_principe: "8 note alternando tono e semitono — Do–Re–Mib–Fa–Fa#–Sol#–La–Si",
    tech_d1_effet: "Colore ambiguo e simmetrico — la tonalità è impossibile da stabilire (la scala si ripete a distanza di terza minore).",
    tech_d2_nom: "Planing (omoritmia parallela)",
    tech_d2_principe: "Tutte le voci si muovono allo stesso ritmo con lo stesso tipo di accordo trasposto",
    tech_d2_effet: "L'accordo si sposta come un blocco sonoro — le quinte parallele sono intenzionali e creano il caratteristico effetto di scivolamento.",
    tech_d3_nom: "Pedale lunga",
    tech_d3_principe: "Basso immobile (nota tenuta) mentre l'armonia cambia liberamente sopra",
    tech_d3_effet: "Sospensione temporale — il tempo armonico si ferma nel basso. Tecnica medievale (organum) reinventata.",
    tech_d4_nom: "Quinte aperte medievali",
    tech_d4_principe: "Accordo di fondamentale + quinta senza terza — né maggiore né minore",
    tech_d4_effet: "Purezza arcaica e atemporale, evocazione del canto gregoriano e delle campane (La Cattedrale Sommersa).",

    step1_label: "Identificare la scala sorgente",
    step1_desc: "Per toni (6 toni interi), ottatonica (tono-semitono), pentatonica o modo ecclesiastico?",
    step2_label: "Individuare la tecnica di texture",
    step2_desc: "Planing? Pedale lunga? Quinte aperte? Omoritmia parallela?",
    step3_label: "Analizzare il colore dell'accordo",
    step3_desc: "Qualità dell'accordo, estensioni presenti, registro. Nessuna funzione armonica.",
    step4_label: "Osservare registro e dinamica",
    step4_desc: "I cambiamenti di colore vengono spesso dal registro e dal volume, non dalla progressione armonica.",

    ravelH2: "L'armonia calcolata di Ravel",
    ravelP: "Ravel condivide con Debussy la superficie impressionista — accordi colorati, estensioni, modi — ma la sua logica è opposta. Ravel si definiva 'orologiaio': ogni accordo è calcolato, ogni voicing misurato. La Pavana, il Bolero, le Valses nobles sono costruzioni architettoniche mascherate da fantasie.",
    ravelInfoBox: "<strong>Differenza essenziale:</strong> Debussy crea intuitivamente per immagini e colori sonori. Ravel calcola con rigore quasi matematico. Stessa superficie impressionista, logiche compositive opposte. Debussy stesso li distingueva chiaramente e si rifiutava di essere associato a Ravel.",
    ravelH3Techniques: "5 tecniche armoniche di Ravel",
    ravelH3Satie: "Satie: il precursore dimenticato",

    tech_r0_nom: "Poliacordo (sovrapposizione)",
    tech_r0_principe: "Due accordi completi sovrapposti — Do Mag + Re Mag = cluster ibrido",
    tech_r0_effet: "Colore armonico denso e inedito — entrambi gli accordi restano riconoscibili ma creano qualcosa di nuovo.",
    tech_r1_nom: "Nota aggiunta (6ª o 9ª)",
    tech_r1_principe: "Arricchimento dell'accordo senza 7ª — CMaj6: Do–Mi–Sol–La",
    tech_r1_effet: "Dolcezza luminosa — meno 'jazz' del Maj7, più 'naïf' e tenero. Firma dello stile raveliano.",
    tech_r2_nom: "Add9 (9ª senza 7ª)",
    tech_r2_principe: "Accordo maggiore + 9ª: Do–Mi–Sol–Re — 9ª senza 7ª intermedia",
    tech_r2_effet: "Apertura e chiarezza — l'accordo sembra aspirare verso l'alto. Molto diverso da Maj9 (che aggiunge anche la 7ª).",
    tech_r3_nom: "Modalità neoclassica",
    tech_r3_principe: "Modi antichi (dorico, frigio, lidio) in un linguaggio moderno",
    tech_r3_effet: "Colore modale senza arcaismo — il modo dorico su Sol dà una luce particolare assente dal minore armonico.",
    tech_r4_nom: "Ostinato armonico (Bolero)",
    tech_r4_principe: "Un solo accordo (Do7) per 15 minuti — la tensione viene dall'orchestrazione progressiva",
    tech_r4_effet: "Dimostrazione che la progressione armonica non è il solo motore di tensione — il timbro e la dinamica bastano.",

    satieName: "Erik Satie (1866–1925)",
    satieP: "Satie precede Debussy e Ravel e anticipa il minimalismo di 50 anni. Le sue <strong>Gymnopédies</strong> (1888) usano accordi di 7ª maggiore in lento dondolio — due colori che si alternano senza mai progredire drammaticamente. Le sue <strong>Vexations</strong> (1893, scoperte dopo la sua morte) anticipano Steve Reich: un pezzo di 52 secondi da suonare 840 volte di fila.",
    satieAccord1Label: "Gymnopédie n°1 — accordo I (Re Mag7)",
    satieAccord1Btn: "▶ Accordo I (Dmaj7)",
    satieAccord2Label: "Accordo IV (Sol Mag7)",
    satieAccord2Btn: "▶ Accordo IV (Gmaj7)",

    ravelWarnBox: "<strong>Errore frequente:</strong> Credere che Debussy e Ravel siano lo stesso compositore con lo stesso stile. La loro superficie è simile (impressionismo, colori) ma il loro metodo è opposto. Ravel può scrivere in forme classiche severe (Sonatina per pianoforte, Quartetto d'archi) con un linguaggio impressionista. Debussy evita le forme classiche. Questa differenza è fondamentale.",

    quizH2: "Quiz — Impressionismo: Debussy, Ravel, Satie",
    ecouter: "▶ Ascolta",
  },

  pt: {
    maitreCardConcept: "Harmonia estática e impressionismo precursor",
    maitreCardAnecdote: "Satie inventou a 'música de mobiliário' (1920) — uma música destinada a se confundir com o ruído ambiente, como um móvel sonoro. Na sua primeira execução, o público sentou-se educadamente e ouviu. Satie, furioso, percorria a sala gritando: 'Falem! Movam-se! Não ouçam!' Ele prefigurava Brian Eno e a música ambiente em 50 anos.",
    maitreCardLesson: "A música pode existir sem tensão nem resolução — a cor harmônica é um fim em si mesma.",

    debussyH2: "A harmonia impressionista de Debussy",
    debussyP: "Debussy dissolveu o sistema tonal clássico não o rejeitando, mas contornando-o. Ele substituiu as funções harmônicas (T/SD/D) por cores sonoras — o acorde não tem mais um papel, tem uma textura. A tensão-resolução cede lugar à atmosfera.",
    debussyInfoBox: "<strong>Princípio fundamental:</strong> Em Debussy, a progressão harmônica segue a melodia e a imagem sonora — não a lógica funcional. Analisar Debussy com as funções T/SD/D é como aplicar as regras do xadrez aos dados. A grelha de análise é inadequada.",
    debussyH3Techniques: "5 técnicas harmônicas características",
    debussyH3Analyser: "Como analisar uma peça impressionista",
    debussyWarnBox: "<strong>Erro clássico:</strong> Procurar cadências V→I em Debussy. Debussy evita-as sistematicamente — é o próprio princípio da sua estética. O Prelúdio à tarde de um fauno (110 compassos) não contém nenhuma cadência dominante-tônica clássica. A harmonia 'flutua' sem nunca se resolver.",

    tech_d0_nom: "Escala de tons inteiros",
    tech_d0_principe: "6 tons inteiros sem semitom — Dó–Ré–Mi–Fá#–Sol#–Lá#",
    tech_d0_effet: "Flutuação total: sem sensível, nenhuma nota atrai a seguinte. Todos os acordes são aumentados.",
    tech_d1_nom: "Escala octatônica (tom-semitom)",
    tech_d1_principe: "8 notas alternando tom e semitom — Dó–Ré–Mib–Fá–Fá#–Sol#–Lá–Si",
    tech_d1_effet: "Cor ambígua e simétrica — a tonalidade é impossível de estabelecer (a escala repete-se a distância de terça menor).",
    tech_d2_nom: "Planing (homorritmo paralelo)",
    tech_d2_principe: "Todas as vozes movem-se no mesmo ritmo com o mesmo tipo de acorde transposto",
    tech_d2_effet: "O acorde desloca-se como um bloco sonoro — as quintas paralelas são intencionais, criando o efeito de deslizamento característico.",
    tech_d3_nom: "Pedal longa",
    tech_d3_principe: "Baixo imóvel (nota sustentada) enquanto a harmonia muda livremente acima",
    tech_d3_effet: "Suspensão temporal — o tempo harmônico para no baixo. Técnica medieval (organum) reinventada.",
    tech_d4_nom: "Quintas abertas medievais",
    tech_d4_principe: "Acorde de fundamental + quinta sem terça — nem maior nem menor",
    tech_d4_effet: "Pureza arcaica e atemporal, evocação do cantochão e dos sinos (A Catedral Submersa).",

    step1_label: "Identificar a escala fonte",
    step1_desc: "Por tons (6 tons inteiros), octatônica (tom-semitom), pentatônica ou modo eclesiástico?",
    step2_label: "Identificar a técnica de textura",
    step2_desc: "Planing? Pedal longa? Quintas abertas? Homorritmo paralelo?",
    step3_label: "Analisar a cor do acorde",
    step3_desc: "Qualidade do acorde, extensões presentes, registro. Sem função harmônica.",
    step4_label: "Observar registro e dinâmica",
    step4_desc: "As mudanças de cor vêm frequentemente do registro e do volume, não da progressão de acordes.",

    ravelH2: "A harmonia calculada de Ravel",
    ravelP: "Ravel partilha com Debussy a superfície impressionista — acordes coloridos, extensões, modos — mas a sua lógica é oposta. Ravel definia-se a si mesmo como um 'relojoeiro': cada acorde é calculado, cada voicing medido. A Pavana, o Bolero, as Valses nobles são construções arquitetônicas disfarçadas de devaneios.",
    ravelInfoBox: "<strong>Diferença essencial:</strong> Debussy cria intuitivamente por imagens e cores sonoras. Ravel calcula com rigor quase matemático. Mesma superfície impressionista, lógicas composicionais opostas. O próprio Debussy os distinguia claramente e recusava ser associado a Ravel.",
    ravelH3Techniques: "5 técnicas harmônicas de Ravel",
    ravelH3Satie: "Satie: o precursor esquecido",

    tech_r0_nom: "Poliacorde (superposição)",
    tech_r0_principe: "Dois acordes completos sobrepostos — Dó Maj + Ré Maj = cluster híbrido",
    tech_r0_effet: "Cor harmônica densa e inédita — os dois acordes permanecem reconhecíveis mas criam algo novo.",
    tech_r1_nom: "Nota acrescentada (6ª ou 9ª)",
    tech_r1_principe: "Enriquecimento do acorde sem 7ª — CMaj6: Dó–Mi–Sol–Lá",
    tech_r1_effet: "Suavidade luminosa — menos 'jazz' do que o Maj7, mais 'ingénuo' e terno. Assinatura do estilo raveliano.",
    tech_r2_nom: "Add9 (9ª sem 7ª)",
    tech_r2_principe: "Acorde maior + 9ª: Dó–Mi–Sol–Ré — 9ª sem 7ª intermédia",
    tech_r2_effet: "Abertura e clareza — o acorde parece aspirar para cima. Muito diferente do Maj9 (que também acrescenta a 7ª).",
    tech_r3_nom: "Modalidade neoclássica",
    tech_r3_principe: "Modos antigos (dórico, frígio, lídio) numa linguagem moderna",
    tech_r3_effet: "Cor modal sem arcaísmo — o modo dórico em Sol dá uma luz particular ausente do menor harmônico.",
    tech_r4_nom: "Ostinato harmônico (Bolero)",
    tech_r4_principe: "Um único acorde (Dó7) durante 15 minutos — a tensão vem da orquestração progressiva",
    tech_r4_effet: "Demonstração de que a progressão harmônica não é o único motor de tensão — o timbre e a dinâmica bastam.",

    satieName: "Erik Satie (1866–1925)",
    satieP: "Satie precede Debussy e Ravel e prefigura o minimalismo em 50 anos. As suas <strong>Gymnopédies</strong> (1888) usam acordes de 7ª maior em balanço lento — duas cores que alternam sem nunca progredir dramaticamente. As suas <strong>Vexations</strong> (1893, descobertas após a sua morte) antecipam Steve Reich: uma peça de 52 segundos a tocar 840 vezes seguidas.",
    satieAccord1Label: "Gymnopédie n°1 — acorde I (Ré Maj7)",
    satieAccord1Btn: "▶ Acorde I (Dmaj7)",
    satieAccord2Label: "Acorde IV (Sol Maj7)",
    satieAccord2Btn: "▶ Acorde IV (Gmaj7)",

    ravelWarnBox: "<strong>Erro frequente:</strong> Acreditar que Debussy e Ravel são o mesmo compositor com o mesmo estilo. A sua superfície é semelhante (impressionismo, cores) mas o seu método é oposto. Ravel pode escrever em formas clássicas rigorosas (Sonatina para piano, Quarteto de cordas) com uma linguagem impressionista. Debussy evita as formas clássicas. Esta diferença é fundamental.",

    quizH2: "Quiz — Impressionismo: Debussy, Ravel, Satie",
    ecouter: "▶ Ouvir",
  },
};

['fr', 'en', 'de', 'es', 'it', 'pt'].forEach(lang => {
  const filePath = `./messages/${lang}.json`;
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!data['cours36']) data['cours36'] = {};
  data['cours36'].narrative = { ...(data['cours36'].narrative || {}), ...NARRATIVE[lang] };
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`${lang} updated`);
});
