const fs = require('fs');

const NARRATIVE = {
  fr: {
    // ── Schenker section ──────────────────────────────────────────────────
    schenkerH2: "L'analyse schenkérienne",
    schenkerP: "Heinrich Schenker (1868–1935) a développé une théorie selon laquelle toute musique tonale est une ornementalisation d'une structure fondamentale simple — l'Ursatz. Son approche révèle les couches de signification cachées sous la surface de la musique.",
    schenkerInfoBox: "<strong>L'Ursatz :</strong> L'Urlinie (ligne mélodique descendante du 5e, 3e ou 8e degré vers la tonique) soutenue par le Bassbrechung (basse qui arpège I–V–I). Toute la musique tonale est une prolongation et ornementalisation de cet Ursatz. En Do majeur : Sol–Fa–Mi–Ré–Do (dessus) / Do–Sol–Do (basse).",
    urlinieLabel: "Urlinie 5̂→1̂ (Do majeur)",
    urlinieNotes: "Sol–Fa–Mi–Ré–Do",
    urlinieBtn: "▶ Écouter l'Urlinie",
    bassLabel: "Bassbrechung I–V–I",
    bassNotes: "Do–Sol–Do (basse)",
    bassBtn: "▶ Écouter la basse",
    niveauxH3: "4 niveaux de réduction",
    n0badge: "Niveau 4",
    n0nom: "Vordergrund (premier plan)",
    n0desc: "La surface musicale complète : tous les accords, ornements, mélodies, notes de passage, broderies, arpèges. C'est la musique telle qu'elle est jouée.",
    n0ex: "CMaj–Am7–Dm7–G7–Em–Am–F–G7–CMaj",
    n1badge: "Niveau 3",
    n1nom: "Mittelgrund (plan intermédiaire proche)",
    n1desc: "Réduction éliminant les ornements de surface. Restent les fonctions harmoniques principales et les prolongations.",
    n1ex: "I–VI–II–V–I (cadences principales)",
    n2badge: "Niveau 2",
    n2nom: "Mittelgrund (plan intermédiaire profond)",
    n2desc: "Réduction montrant uniquement les régions tonales et les prolongations harmoniques majeures.",
    n2ex: "I (prolongé sur 16 mesures) → V → I",
    n3badge: "Niveau 1",
    n3nom: "Hintergrund (arrière-plan)",
    n3desc: "La structure fondamentale (Ursatz) : Urlinie + Bassbrechung. La charpente harmonique de toute l'œuvre en quelques notes.",
    n3ex: "Sol–Fa–Mi–Ré–Do / Do–Sol–Do",
    ornementsH3: "Types d'ornementalisation (notes non structurelles)",
    o0nom: "Note de passage",
    o0desc: "Relie deux notes structurelles par mouvement conjoint : Do–Ré–Mi, le Ré disparaît à la réduction",
    o1nom: "Note de broderie",
    o1desc: "Part d'une note structurelle, s'éloigne d'un degré, revient : Do–Ré–Do, le Ré est une broderie",
    o2nom: "Appogiature",
    o2desc: "Note étrangère non préparée sur un temps fort, résolue par mouvement conjoint descendant",
    o3nom: "Retard",
    o3desc: "La résolution d'une note est retardée — la note non structurelle tient sur le temps fort et se résout ensuite",
    schenkerWarn: "<strong>Erreur classique :</strong> Confondre réduction schenkérienne et simplification. La réduction ne supprime pas des notes \"au hasard\" — elle identifie les notes structurelles selon des critères précis (position métrique, durée, rôle harmonique). Les notes ornementales ne sont pas moins importantes : elles sont la surface expressive. La réduction révèle la structure, elle ne juge pas la valeur.",
    // ── Motivique section ─────────────────────────────────────────────────
    motiviqueH2: "Analyse motivique",
    motiviqueP: "L'analyse motivique identifie les cellules mélodiques de 2 à 6 notes qui constituent la matière première d'une œuvre, puis suit leurs transformations. Ce niveau d'analyse révèle l'unité organique d'une composition — comment tout est dérivé de peu.",
    beethInfoBox: "<strong>Beethoven — 5e Symphonie :</strong> Le motif initial (Sol–Sol–Sol–Mib) n'est pas seulement le début du premier mouvement. Ce motif rythmique (3 croches + noire) et mélodique (tierce mineure descendante) organise les 4 mouvements entiers — dans le thème du 2e mouvement, dans les fanfares du 3e, dans la transition finale du 4e. C'est la définition même de l'unité organique.",
    beethCard: "Motif Beethoven 5e — Sol–Sol–Sol–Mib",
    beethDesc: "Deux dimensions simultanées : <strong>rythme</strong> (court–court–court–long) et <strong>mélodie</strong> (tierce mineure descendante). Les deux sont inséparables dans l'analyse. Dans le 2e mouvement, le rythme est transformé mais la tierce mélodique persiste.",
    motifOrigBtn: "▶ Motif original",
    motifTransBtn: "▶ Transposé (même rythme)",
    transformH3: "4 transformations motiviques fondamentales",
    t0nom: "Transposition",
    t0desc: "Le motif transposé à un autre degré — les intervalles sont conservés",
    t0ex: "Beethoven 5e : motif répété dès la 2e mesure un ton plus bas",
    t1nom: "Inversion",
    t1desc: "Les intervalles retournés — ce qui montait descend et vice versa",
    t1ex: "Bach : inversions du sujet dans les fugues",
    t2nom: "Augmentation",
    t2desc: "Le motif en valeurs doubles — plus lent, plus solennel",
    t2ex: "Dans un registre plus aigu pour marquer l'augmentation",
    t3nom: "Fragmentation",
    t3desc: "Seulement les 2–3 premières notes du motif — crée l'inquiétude et l'urgence",
    t3ex: "Beethoven 5e : développement fragmente les 4 notes en 2 + 2",
    labelOriginal: "Original :",
    labelTransforme: "Transformé :",
    labelExemple: "Exemple :",
    methodeH3: "Méthode d'analyse motivique",
    s1label: "Identifier le motif générateur",
    s1desc: "2 à 6 notes qui apparaissent au début et se répètent. Un intervalle ou un rythme distinctif est la clé.",
    s2label: "Cartographier les occurrences",
    s2desc: "Marquer chaque apparition du motif dans la partition — transpositions, transformations incluses.",
    s3label: "Analyser les transformations",
    s3desc: "Inversion, augmentation, diminution, fragmentation, séquence. Comment le motif se développe-t-il ?",
    s4label: "Identifier la fonction structurelle",
    s4desc: "Le motif crée-t-il l'exposition, le développement, le climax ? Quel rôle narratif joue-t-il ?",
    brahmsInfoBox: "<strong>Brahms et l'unité motivique :</strong> Dans ses quatuors et symphonies, Brahms dérive souvent toute l'œuvre d'un seul intervalle (une seconde ou une tierce). Cet intervalle générateur apparaît dans la mélodie, la basse, les transitions, les contre-mélodies — toujours reconnaissable, toujours transformé. L'analyse motivique de Brahms révèle une densité thématique comparable à celle de Bach.",
    motiviqueWarn: "<strong>Erreur courante :</strong> Analyser chaque accord de surface sans chercher la structure profonde. Dire \"Do–Sol–Fa–Do\" ne dit rien sur la signification structurelle. L'analyse motivique complète l'analyse harmonique : d'un côté la structure verticale (accords), de l'autre la structure horizontale (motif et sa destinée). Les deux ensemble révèlent la logique compositionnelle.",
    // ── Quiz section ──────────────────────────────────────────────────────
    quizH2: "Quiz — Schenker et analyse motivique",
  },

  en: {
    schenkerH2: "Schenkerian analysis",
    schenkerP: "Heinrich Schenker (1868–1935) developed a theory according to which all tonal music is an elaboration of a simple fundamental structure — the Ursatz. His approach reveals the layers of meaning hidden beneath the surface of music.",
    schenkerInfoBox: "<strong>The Ursatz:</strong> The Urlinie (descending melodic line from the 5th, 3rd, or 8th degree to the tonic) supported by the Bassbrechung (bass arpeggiation I–V–I). All tonal music is a prolongation and elaboration of this Ursatz. In C major: G–F–E–D–C (soprano) / C–G–C (bass).",
    urlinieLabel: "Urlinie 5̂→1̂ (C major)",
    urlinieNotes: "G–F–E–D–C",
    urlinieBtn: "▶ Listen to Urlinie",
    bassLabel: "Bassbrechung I–V–I",
    bassNotes: "C–G–C (bass)",
    bassBtn: "▶ Listen to bass",
    niveauxH3: "4 levels of reduction",
    n0badge: "Level 4",
    n0nom: "Vordergrund (foreground)",
    n0desc: "The complete musical surface: all chords, ornaments, melodies, passing notes, neighbour notes, arpeggios. This is the music as performed.",
    n0ex: "CMaj–Am7–Dm7–G7–Em–Am–F–G7–CMaj",
    n1badge: "Level 3",
    n1nom: "Mittelgrund (near middleground)",
    n1desc: "Reduction eliminating surface ornaments. Only the main harmonic functions and prolongations remain.",
    n1ex: "I–VI–II–V–I (main cadences)",
    n2badge: "Level 2",
    n2nom: "Mittelgrund (deep middleground)",
    n2desc: "Reduction showing only tonal regions and major harmonic prolongations.",
    n2ex: "I (prolonged over 16 bars) → V → I",
    n3badge: "Level 1",
    n3nom: "Hintergrund (background)",
    n3desc: "The fundamental structure (Ursatz): Urlinie + Bassbrechung. The harmonic framework of the entire work in a few notes.",
    n3ex: "G–F–E–D–C / C–G–C",
    ornementsH3: "Types of elaboration (non-structural notes)",
    o0nom: "Passing note",
    o0desc: "Connects two structural notes by stepwise motion: C–D–E, the D disappears at the reduction level",
    o1nom: "Neighbour note",
    o1desc: "Leaves a structural note, moves one step away, returns: C–D–C, the D is a neighbour note",
    o2nom: "Appoggiatura",
    o2desc: "Unprepared foreign note on a strong beat, resolved by descending stepwise motion",
    o3nom: "Suspension",
    o3desc: "Resolution of a note is delayed — the non-structural note holds on the strong beat and resolves afterwards",
    schenkerWarn: "<strong>Classic mistake:</strong> Confusing Schenkerian reduction with simplification. Reduction does not remove notes \"at random\" — it identifies structural notes according to precise criteria (metric position, duration, harmonic role). Ornamental notes are not less important: they are the expressive surface. Reduction reveals structure; it does not judge value.",
    motiviqueH2: "Motivic analysis",
    motiviqueP: "Motivic analysis identifies the melodic cells of 2 to 6 notes that form the raw material of a work, then tracks their transformations. This level of analysis reveals the organic unity of a composition — how everything derives from very little.",
    beethInfoBox: "<strong>Beethoven — 5th Symphony:</strong> The opening motif (G–G–G–Eb) is not just the beginning of the first movement. This rhythmic (3 eighth notes + quarter note) and melodic (descending minor third) motif organises all 4 movements — in the 2nd movement theme, in the 3rd movement fanfares, in the 4th movement finale transition. This is the very definition of organic unity.",
    beethCard: "Beethoven 5th motif — G–G–G–Eb",
    beethDesc: "Two simultaneous dimensions: <strong>rhythm</strong> (short–short–short–long) and <strong>melody</strong> (descending minor third). Both are inseparable in analysis. In the 2nd movement the rhythm is transformed, but the melodic third persists.",
    motifOrigBtn: "▶ Original motif",
    motifTransBtn: "▶ Transposed (same rhythm)",
    transformH3: "4 fundamental motivic transformations",
    t0nom: "Transposition",
    t0desc: "The motif transposed to another degree — intervals are preserved",
    t0ex: "Beethoven 5th: motif repeated from bar 2 a tone lower",
    t1nom: "Inversion",
    t1desc: "Intervals reversed — what went up now goes down and vice versa",
    t1ex: "Bach: inversions of the subject in fugues",
    t2nom: "Augmentation",
    t2desc: "The motif in doubled values — slower, more solemn",
    t2ex: "In a higher register to mark the augmentation",
    t3nom: "Fragmentation",
    t3desc: "Only the first 2–3 notes of the motif — creates unease and urgency",
    t3ex: "Beethoven 5th: development fragments the 4 notes into 2 + 2",
    labelOriginal: "Original:",
    labelTransforme: "Transformed:",
    labelExemple: "Example:",
    methodeH3: "Motivic analysis method",
    s1label: "Identify the generating motif",
    s1desc: "2 to 6 notes appearing at the start and repeating. A distinctive interval or rhythm is the key.",
    s2label: "Map the occurrences",
    s2desc: "Mark every appearance of the motif in the score — transpositions and transformations included.",
    s3label: "Analyse the transformations",
    s3desc: "Inversion, augmentation, diminution, fragmentation, sequence. How does the motif develop?",
    s4label: "Identify the structural function",
    s4desc: "Does the motif create exposition, development, climax? What narrative role does it play?",
    brahmsInfoBox: "<strong>Brahms and motivic unity:</strong> In his quartets and symphonies, Brahms often derives the entire work from a single interval (a second or a third). This generating interval appears in the melody, the bass, the transitions, the counter-melodies — always recognisable, always transformed. Brahms's motivic analysis reveals a thematic density comparable to Bach's.",
    motiviqueWarn: "<strong>Common mistake:</strong> Analysing each surface chord without seeking the deep structure. Saying \"C–G–F–C\" says nothing about structural significance. Motivic analysis complements harmonic analysis: on one side the vertical structure (chords), on the other the horizontal structure (motif and its destiny). Together they reveal compositional logic.",
    quizH2: "Quiz — Schenker and motivic analysis",
  },

  de: {
    schenkerH2: "Schenkersche Analyse",
    schenkerP: "Heinrich Schenker (1868–1935) entwickelte eine Theorie, nach der alle tonale Musik eine Ausarbeitung einer einfachen Grundstruktur — des Ursatzes — ist. Sein Ansatz enthüllt die Bedeutungsschichten, die unter der musikalischen Oberfläche verborgen sind.",
    schenkerInfoBox: "<strong>Der Ursatz:</strong> Die Urlinie (absteigende melodische Linie vom 5., 3. oder 8. Grad zur Tonika) gestützt durch den Bassbrechung (Bassarpeggiation I–V–I). Alle tonale Musik ist eine Verlängerung und Ausarbeitung dieses Ursatzes. In C-Dur: G–F–E–D–C (Sopran) / C–G–C (Bass).",
    urlinieLabel: "Urlinie 5̂→1̂ (C-Dur)",
    urlinieNotes: "G–F–E–D–C",
    urlinieBtn: "▶ Urlinie anhören",
    bassLabel: "Bassbrechung I–V–I",
    bassNotes: "C–G–C (Bass)",
    bassBtn: "▶ Bass anhören",
    niveauxH3: "4 Reduktionsstufen",
    n0badge: "Stufe 4",
    n0nom: "Vordergrund",
    n0desc: "Die vollständige musikalische Oberfläche: alle Akkorde, Ornamente, Melodien, Durchgangsnoten, Wechselnoten, Arpeggios. Das ist die Musik so, wie sie gespielt wird.",
    n0ex: "CMaj–Am7–Dm7–G7–Em–Am–F–G7–CMaj",
    n1badge: "Stufe 3",
    n1nom: "Mittelgrund (nahe Mittelschicht)",
    n1desc: "Reduktion, die Oberflächenornamente eliminiert. Es bleiben die wichtigsten Harmonikfunktionen und Prolongationen übrig.",
    n1ex: "I–VI–II–V–I (Hauptkadenzen)",
    n2badge: "Stufe 2",
    n2nom: "Mittelgrund (tiefe Mittelschicht)",
    n2desc: "Reduktion, die nur die tonalen Regionen und die wichtigsten harmonischen Prolongationen zeigt.",
    n2ex: "I (über 16 Takte prolongiert) → V → I",
    n3badge: "Stufe 1",
    n3nom: "Hintergrund",
    n3desc: "Die Grundstruktur (Ursatz): Urlinie + Bassbrechung. Das harmonische Gerüst des gesamten Werkes in wenigen Noten.",
    n3ex: "G–F–E–D–C / C–G–C",
    ornementsH3: "Arten der Ausarbeitung (nicht-strukturelle Töne)",
    o0nom: "Durchgangsnote",
    o0desc: "Verbindet zwei Strukturtöne durch Stufenbewegung: C–D–E, das D verschwindet auf der Reduktionsebene",
    o1nom: "Wechselnote",
    o1desc: "Geht von einem Strukturton aus, entfernt sich eine Stufe, kehrt zurück: C–D–C, das D ist eine Wechselnote",
    o2nom: "Appoggiatura",
    o2desc: "Unvorbereiteter Fremdton auf einer starken Zählzeit, durch absteigende Stufenbewegung aufgelöst",
    o3nom: "Vorhalt",
    o3desc: "Die Auflösung eines Tones wird verzögert — der nicht-strukturelle Ton hält auf der starken Zählzeit und löst sich danach auf",
    schenkerWarn: "<strong>Klassischer Fehler:</strong> Schenkersche Reduktion mit Vereinfachung verwechseln. Reduktion entfernt keine Töne &bdquo;zufällig&ldquo; — sie identifiziert Strukturtöne nach präzisen Kriterien (metrische Position, Dauer, harmonische Rolle). Ornamentale Töne sind nicht weniger wichtig: sie sind die expressive Oberfläche. Reduktion enthüllt die Struktur, sie bewertet nicht den künstlerischen Wert.",
    motiviqueH2: "Motivische Analyse",
    motiviqueP: "Die motivische Analyse identifiziert melodische Zellen von 2 bis 6 Tönen, die das Rohmaterial eines Werkes bilden, und verfolgt ihre Transformationen. Diese Analyseebene enthüllt die organische Einheit einer Komposition — wie alles aus sehr wenig abgeleitet wird.",
    beethInfoBox: "<strong>Beethoven — 5. Symphonie:</strong> Das Anfangsmotiv (G–G–G–Es) ist nicht nur der Beginn des ersten Satzes. Dieses rhythmische (3 Achtel + Viertel) und melodische (absteigende Moll-Terz) Motiv organisiert alle 4 Sätze — im Thema des 2. Satzes, in den Fanfaren des 3. Satzes, im Übergang des Finalsatzes. Das ist die Definition organischer Einheit.",
    beethCard: "Beethoven 5. Motiv — G–G–G–Es",
    beethDesc: "Zwei gleichzeitige Dimensionen: <strong>Rhythmus</strong> (kurz–kurz–kurz–lang) und <strong>Melodie</strong> (absteigende Moll-Terz). Beide sind in der Analyse untrennbar. Im 2. Satz ist der Rhythmus transformiert, aber die melodische Terz bleibt bestehen.",
    motifOrigBtn: "▶ Originalmotiv",
    motifTransBtn: "▶ Transponiert (gleicher Rhythmus)",
    transformH3: "4 grundlegende motivische Transformationen",
    t0nom: "Transposition",
    t0desc: "Das Motiv auf eine andere Stufe transponiert — die Intervalle bleiben erhalten",
    t0ex: "Beethoven 5.: Motiv ab Takt 2 einen Ton tiefer wiederholt",
    t1nom: "Umkehrung",
    t1desc: "Intervalle umgekehrt — was stieg, fällt nun und umgekehrt",
    t1ex: "Bach: Umkehrungen des Themas in Fugen",
    t2nom: "Augmentation",
    t2desc: "Das Motiv in verdoppelten Notenwerten — langsamer, feierlicher",
    t2ex: "In einer höheren Lage, um die Augmentation zu markieren",
    t3nom: "Fragmentierung",
    t3desc: "Nur die ersten 2–3 Noten des Motivs — erzeugt Unruhe und Dringlichkeit",
    t3ex: "Beethoven 5.: Durchführung fragmentiert die 4 Noten in 2 + 2",
    labelOriginal: "Original:",
    labelTransforme: "Transformiert:",
    labelExemple: "Beispiel:",
    methodeH3: "Methode der motivischen Analyse",
    s1label: "Das erzeugende Motiv identifizieren",
    s1desc: "2 bis 6 Töne, die zu Beginn erscheinen und sich wiederholen. Ein markantes Intervall oder ein markanter Rhythmus ist der Schlüssel.",
    s2label: "Die Vorkommen kartieren",
    s2desc: "Jedes Auftreten des Motivs in der Partitur markieren — Transpositionen und Transformationen eingeschlossen.",
    s3label: "Die Transformationen analysieren",
    s3desc: "Umkehrung, Augmentation, Diminution, Fragmentierung, Sequenz. Wie entwickelt sich das Motiv?",
    s4label: "Die strukturelle Funktion identifizieren",
    s4desc: "Schafft das Motiv Exposition, Durchführung, Höhepunkt? Welche narrative Rolle spielt es?",
    brahmsInfoBox: "<strong>Brahms und motivische Einheit:</strong> In seinen Quartetten und Symphonien leitet Brahms oft das gesamte Werk von einem einzigen Intervall (einer Sekunde oder Terz) ab. Dieses erzeugende Intervall erscheint in der Melodie, dem Bass, den Übergängen, den Gegenstimmen — immer erkennbar, immer transformiert. Brahms' motivische Analyse enthüllt eine thematische Dichte, die mit Bach vergleichbar ist.",
    motiviqueWarn: "<strong>Häufiger Fehler:</strong> Jeden Oberflächenakkord analysieren, ohne nach der Tiefenstruktur zu suchen. &bdquo;C–G–F–C&ldquo; zu sagen, sagt nichts über strukturelle Bedeutung aus. Motivische Analyse ergänzt die harmonische Analyse: auf der einen Seite die vertikale Struktur (Akkorde), auf der anderen die horizontale Struktur (Motiv und sein Schicksal). Zusammen enthüllen sie die kompositorische Logik.",
    quizH2: "Quiz — Schenker und motivische Analyse",
  },

  es: {
    schenkerH2: "El análisis schenkeriano",
    schenkerP: "Heinrich Schenker (1868–1935) desarrolló una teoría según la cual toda la música tonal es una ornamentación de una estructura fundamental simple — el Ursatz. Su enfoque revela las capas de significado ocultas bajo la superficie de la música.",
    schenkerInfoBox: "<strong>El Ursatz:</strong> La Urlinie (línea melódica descendente desde el 5.º, 3.º u 8.º grado hacia la tónica) sostenida por el Bassbrechung (arpegio del bajo I–V–I). Toda la música tonal es una prolongación y ornamentación de este Ursatz. En Do mayor: Sol–Fa–Mi–Re–Do (soprano) / Do–Sol–Do (bajo).",
    urlinieLabel: "Urlinie 5̂→1̂ (Do mayor)",
    urlinieNotes: "Sol–Fa–Mi–Re–Do",
    urlinieBtn: "▶ Escuchar la Urlinie",
    bassLabel: "Bassbrechung I–V–I",
    bassNotes: "Do–Sol–Do (bajo)",
    bassBtn: "▶ Escuchar el bajo",
    niveauxH3: "4 niveles de reducción",
    n0badge: "Nivel 4",
    n0nom: "Vordergrund (primer plano)",
    n0desc: "La superficie musical completa: todos los acordes, ornamentos, melodías, notas de paso, bordaduras, arpegios. Es la música tal como se interpreta.",
    n0ex: "CMaj–Am7–Dm7–G7–Em–Am–F–G7–CMaj",
    n1badge: "Nivel 3",
    n1nom: "Mittelgrund (plano intermedio cercano)",
    n1desc: "Reducción que elimina los ornamentos de superficie. Quedan las funciones armónicas principales y las prolongaciones.",
    n1ex: "I–VI–II–V–I (cadencias principales)",
    n2badge: "Nivel 2",
    n2nom: "Mittelgrund (plano intermedio profundo)",
    n2desc: "Reducción que muestra únicamente las regiones tonales y las prolongaciones armónicas mayores.",
    n2ex: "I (prolongado durante 16 compases) → V → I",
    n3badge: "Nivel 1",
    n3nom: "Hintergrund (plano de fondo)",
    n3desc: "La estructura fundamental (Ursatz): Urlinie + Bassbrechung. El armazón armónico de toda la obra en pocas notas.",
    n3ex: "Sol–Fa–Mi–Re–Do / Do–Sol–Do",
    ornementsH3: "Tipos de ornamentación (notas no estructurales)",
    o0nom: "Nota de paso",
    o0desc: "Une dos notas estructurales por movimiento conjunto: Do–Re–Mi, el Re desaparece en la reducción",
    o1nom: "Nota bordado",
    o1desc: "Sale de una nota estructural, se aleja un grado, regresa: Do–Re–Do, el Re es una bordadura",
    o2nom: "Apoyatura",
    o2desc: "Nota extraña no preparada en un tiempo fuerte, resuelta por movimiento conjunto descendente",
    o3nom: "Retardo",
    o3desc: "La resolución de una nota se retrasa — la nota no estructural se mantiene en el tiempo fuerte y se resuelve después",
    schenkerWarn: "<strong>Error clásico:</strong> Confundir la reducción schenkeriana con la simplificación. La reducción no elimina notas \"al azar\" — identifica las notas estructurales según criterios precisos (posición métrica, duración, papel armónico). Las notas ornamentales no son menos importantes: son la superficie expresiva. La reducción revela la estructura, no juzga el valor.",
    motiviqueH2: "Análisis motívico",
    motiviqueP: "El análisis motívico identifica las células melódicas de 2 a 6 notas que constituyen la materia prima de una obra, y luego sigue sus transformaciones. Este nivel de análisis revela la unidad orgánica de una composición — cómo todo se deriva de muy poco.",
    beethInfoBox: "<strong>Beethoven — 5.ª Sinfonía:</strong> El motivo inicial (Sol–Sol–Sol–Mib) no es solo el comienzo del primer movimiento. Este motivo rítmico (3 corcheas + negra) y melódico (tercera menor descendente) organiza los 4 movimientos completos — en el tema del 2.º movimiento, en las fanfarrias del 3.º, en la transición final del 4.º. Es la definición misma de la unidad orgánica.",
    beethCard: "Motivo de Beethoven 5.ª — Sol–Sol–Sol–Mib",
    beethDesc: "Dos dimensiones simultáneas: <strong>ritmo</strong> (corto–corto–corto–largo) y <strong>melodía</strong> (tercera menor descendente). Ambas son inseparables en el análisis. En el 2.º movimiento el ritmo se transforma, pero la tercera melódica persiste.",
    motifOrigBtn: "▶ Motivo original",
    motifTransBtn: "▶ Transportado (mismo ritmo)",
    transformH3: "4 transformaciones motívicas fundamentales",
    t0nom: "Transposición",
    t0desc: "El motivo transportado a otro grado — los intervalos se conservan",
    t0ex: "Beethoven 5.ª: motivo repetido desde el 2.º compás un tono más bajo",
    t1nom: "Inversión",
    t1desc: "Los intervalos invertidos — lo que subía ahora baja y viceversa",
    t1ex: "Bach: inversiones del sujeto en las fugas",
    t2nom: "Aumentación",
    t2desc: "El motivo en valores dobles — más lento, más solemne",
    t2ex: "En un registro más agudo para marcar la aumentación",
    t3nom: "Fragmentación",
    t3desc: "Solo las primeras 2–3 notas del motivo — crea inquietud y urgencia",
    t3ex: "Beethoven 5.ª: el desarrollo fragmenta las 4 notas en 2 + 2",
    labelOriginal: "Original:",
    labelTransforme: "Transformado:",
    labelExemple: "Ejemplo:",
    methodeH3: "Método de análisis motívico",
    s1label: "Identificar el motivo generador",
    s1desc: "2 a 6 notas que aparecen al inicio y se repiten. Un intervalo o ritmo distintivo es la clave.",
    s2label: "Cartografiar las ocurrencias",
    s2desc: "Marcar cada aparición del motivo en la partitura — transposiciones y transformaciones incluidas.",
    s3label: "Analizar las transformaciones",
    s3desc: "Inversión, aumentación, disminución, fragmentación, secuencia. ¿Cómo se desarrolla el motivo?",
    s4label: "Identificar la función estructural",
    s4desc: "¿El motivo crea la exposición, el desarrollo, el clímax? ¿Qué papel narrativo juega?",
    brahmsInfoBox: "<strong>Brahms y la unidad motívica:</strong> En sus cuartetos y sinfonías, Brahms deriva a menudo toda la obra de un único intervalo (una segunda o una tercera). Este intervalo generador aparece en la melodía, el bajo, las transiciones, las contramelodías — siempre reconocible, siempre transformado. El análisis motívico de Brahms revela una densidad temática comparable a la de Bach.",
    motiviqueWarn: "<strong>Error frecuente:</strong> Analizar cada acorde de superficie sin buscar la estructura profunda. Decir \"Do–Sol–Fa–Do\" no dice nada sobre la significación estructural. El análisis motívico complementa el análisis armónico: por un lado la estructura vertical (acordes), por el otro la estructura horizontal (motivo y su destino). Ambos juntos revelan la lógica compositiva.",
    quizH2: "Quiz — Schenker y análisis motívico",
  },

  it: {
    schenkerH2: "L'analisi schenkeriana",
    schenkerP: "Heinrich Schenker (1868–1935) ha sviluppato una teoria secondo cui tutta la musica tonale è un'ornamentazione di una struttura fondamentale semplice — l'Ursatz. Il suo approccio rivela gli strati di significato nascosti sotto la superficie della musica.",
    schenkerInfoBox: "<strong>L'Ursatz:</strong> L'Urlinie (linea melodica discendente dal 5°, 3° o 8° grado verso la tonica) sostenuta dal Bassbrechung (arpeggio del basso I–V–I). Tutta la musica tonale è una prolungazione e ornamentazione di questo Ursatz. In Do maggiore: Sol–Fa–Mi–Re–Do (soprano) / Do–Sol–Do (basso).",
    urlinieLabel: "Urlinie 5̂→1̂ (Do maggiore)",
    urlinieNotes: "Sol–Fa–Mi–Re–Do",
    urlinieBtn: "▶ Ascolta l'Urlinie",
    bassLabel: "Bassbrechung I–V–I",
    bassNotes: "Do–Sol–Do (basso)",
    bassBtn: "▶ Ascolta il basso",
    niveauxH3: "4 livelli di riduzione",
    n0badge: "Livello 4",
    n0nom: "Vordergrund (primo piano)",
    n0desc: "La superficie musicale completa: tutti gli accordi, ornamenti, melodie, note di passaggio, note di bordatura, arpeggi. È la musica così come viene eseguita.",
    n0ex: "CMaj–Am7–Dm7–G7–Em–Am–F–G7–CMaj",
    n1badge: "Livello 3",
    n1nom: "Mittelgrund (piano intermedio vicino)",
    n1desc: "Riduzione che elimina gli ornamenti di superficie. Rimangono le principali funzioni armoniche e le prolungazioni.",
    n1ex: "I–VI–II–V–I (cadenze principali)",
    n2badge: "Livello 2",
    n2nom: "Mittelgrund (piano intermedio profondo)",
    n2desc: "Riduzione che mostra solo le regioni tonali e le principali prolungazioni armoniche.",
    n2ex: "I (prolungato per 16 misure) → V → I",
    n3badge: "Livello 1",
    n3nom: "Hintergrund (sfondo)",
    n3desc: "La struttura fondamentale (Ursatz): Urlinie + Bassbrechung. L'ossatura armonica dell'intera opera in poche note.",
    n3ex: "Sol–Fa–Mi–Re–Do / Do–Sol–Do",
    ornementsH3: "Tipi di ornamentazione (note non strutturali)",
    o0nom: "Nota di passaggio",
    o0desc: "Collega due note strutturali per moto congiunto: Do–Re–Mi, il Re scompare alla riduzione",
    o1nom: "Nota di broderia",
    o1desc: "Parte da una nota strutturale, si allontana di un grado, ritorna: Do–Re–Do, il Re è una broderia",
    o2nom: "Appoggiatura",
    o2desc: "Nota estranea non preparata su un tempo forte, risolta per moto congiunto discendente",
    o3nom: "Ritardo",
    o3desc: "La risoluzione di una nota viene ritardata — la nota non strutturale tiene sul tempo forte e si risolve dopo",
    schenkerWarn: "<strong>Errore classico:</strong> Confondere la riduzione schenkeriana con la semplificazione. La riduzione non elimina note \"a caso\" — identifica le note strutturali secondo criteri precisi (posizione metrica, durata, ruolo armonico). Le note ornamentali non sono meno importanti: sono la superficie espressiva. La riduzione rivela la struttura, non giudica il valore.",
    motiviqueH2: "Analisi motivica",
    motiviqueP: "L'analisi motivica identifica le cellule melodiche da 2 a 6 note che costituiscono la materia prima di un'opera, poi ne segue le trasformazioni. Questo livello di analisi rivela l'unità organica di una composizione — come tutto deriva da poco.",
    beethInfoBox: "<strong>Beethoven — 5ª Sinfonia:</strong> Il motivo iniziale (Sol–Sol–Sol–Mib) non è solo l'inizio del primo movimento. Questo motivo ritmico (3 crome + semiminima) e melodico (terza minore discendente) organizza tutti e 4 i movimenti — nel tema del 2° movimento, nelle fanfare del 3°, nella transizione finale del 4°. È la definizione stessa di unità organica.",
    beethCard: "Motivo Beethoven 5ª — Sol–Sol–Sol–Mib",
    beethDesc: "Due dimensioni simultanee: <strong>ritmo</strong> (corto–corto–corto–lungo) e <strong>melodia</strong> (terza minore discendente). Entrambe sono inseparabili nell'analisi. Nel 2° movimento il ritmo si trasforma, ma la terza melodica persiste.",
    motifOrigBtn: "▶ Motivo originale",
    motifTransBtn: "▶ Trasposto (stesso ritmo)",
    transformH3: "4 trasformazioni motiviche fondamentali",
    t0nom: "Trasposizione",
    t0desc: "Il motivo trasposto a un altro grado — gli intervalli sono conservati",
    t0ex: "Beethoven 5ª: motivo ripetuto dalla 2ª misura un tono più basso",
    t1nom: "Inversione",
    t1desc: "Gli intervalli capovolti — ciò che saliva ora scende e viceversa",
    t1ex: "Bach: inversioni del soggetto nelle fughe",
    t2nom: "Aumentazione",
    t2desc: "Il motivo in valori doppi — più lento, più solenne",
    t2ex: "In un registro più acuto per segnare l'aumentazione",
    t3nom: "Frammentazione",
    t3desc: "Solo le prime 2–3 note del motivo — crea inquietudine e urgenza",
    t3ex: "Beethoven 5ª: lo sviluppo frammenta le 4 note in 2 + 2",
    labelOriginal: "Originale:",
    labelTransforme: "Trasformato:",
    labelExemple: "Esempio:",
    methodeH3: "Metodo di analisi motivica",
    s1label: "Identificare il motivo generatore",
    s1desc: "Da 2 a 6 note che appaiono all'inizio e si ripetono. Un intervallo o un ritmo caratteristico è la chiave.",
    s2label: "Cartografare le occorrenze",
    s2desc: "Segnare ogni apparizione del motivo nella partitura — trasposizioni e trasformazioni incluse.",
    s3label: "Analizzare le trasformazioni",
    s3desc: "Inversione, aumentazione, diminuzione, frammentazione, sequenza. Come si sviluppa il motivo?",
    s4label: "Identificare la funzione strutturale",
    s4desc: "Il motivo crea l'esposizione, lo sviluppo, il climax? Che ruolo narrativo svolge?",
    brahmsInfoBox: "<strong>Brahms e l'unità motivica:</strong> Nei suoi quartetti e sinfonie, Brahms spesso deriva tutta l'opera da un unico intervallo (una seconda o una terza). Questo intervallo generatore appare nella melodia, nel basso, nelle transizioni, nei controcanti — sempre riconoscibile, sempre trasformato. L'analisi motivica di Brahms rivela una densità tematica paragonabile a quella di Bach.",
    motiviqueWarn: "<strong>Errore comune:</strong> Analizzare ogni accordo di superficie senza cercare la struttura profonda. Dire \"Do–Sol–Fa–Do\" non dice nulla sulla significazione strutturale. L'analisi motivica completa l'analisi armonica: da un lato la struttura verticale (accordi), dall'altro la struttura orizzontale (motivo e il suo destino). Entrambe insieme rivelano la logica compositiva.",
    quizH2: "Quiz — Schenker e analisi motivica",
  },

  pt: {
    schenkerH2: "A análise schenkeriana",
    schenkerP: "Heinrich Schenker (1868–1935) desenvolveu uma teoria segundo a qual toda a música tonal é uma ornamentação de uma estrutura fundamental simples — o Ursatz. A sua abordagem revela as camadas de significado escondidas sob a superfície da música.",
    schenkerInfoBox: "<strong>O Ursatz:</strong> A Urlinie (linha melódica descendente do 5.º, 3.º ou 8.º grau para a tônica) sustentada pelo Bassbrechung (arpeggiation do baixo I–V–I). Toda a música tonal é uma prolongação e ornamentação deste Ursatz. Em Dó maior: Sol–Fá–Mi–Ré–Dó (soprano) / Dó–Sol–Dó (baixo).",
    urlinieLabel: "Urlinie 5̂→1̂ (Dó maior)",
    urlinieNotes: "Sol–Fá–Mi–Ré–Dó",
    urlinieBtn: "▶ Ouvir a Urlinie",
    bassLabel: "Bassbrechung I–V–I",
    bassNotes: "Dó–Sol–Dó (baixo)",
    bassBtn: "▶ Ouvir o baixo",
    niveauxH3: "4 níveis de redução",
    n0badge: "Nível 4",
    n0nom: "Vordergrund (primeiro plano)",
    n0desc: "A superfície musical completa: todos os acordes, ornamentos, melodias, notas de passagem, bordaduras, arpejos. É a música tal como é tocada.",
    n0ex: "CMaj–Am7–Dm7–G7–Em–Am–F–G7–CMaj",
    n1badge: "Nível 3",
    n1nom: "Mittelgrund (plano intermédio próximo)",
    n1desc: "Redução que elimina os ornamentos de superfície. Ficam as principais funções harmónicas e as prolongações.",
    n1ex: "I–VI–II–V–I (cadências principais)",
    n2badge: "Nível 2",
    n2nom: "Mittelgrund (plano intermédio profundo)",
    n2desc: "Redução que mostra apenas as regiões tonais e as principais prolongações harmónicas.",
    n2ex: "I (prolongado durante 16 compassos) → V → I",
    n3badge: "Nível 1",
    n3nom: "Hintergrund (plano de fundo)",
    n3desc: "A estrutura fundamental (Ursatz): Urlinie + Bassbrechung. O esqueleto harmónico de toda a obra em poucas notas.",
    n3ex: "Sol–Fá–Mi–Ré–Dó / Dó–Sol–Dó",
    ornementsH3: "Tipos de ornamentação (notas não estruturais)",
    o0nom: "Nota de passagem",
    o0desc: "Liga duas notas estruturais por movimento conjunto: Dó–Ré–Mi, o Ré desaparece na redução",
    o1nom: "Nota de bordadura",
    o1desc: "Parte de uma nota estrutural, afasta-se um grau, regressa: Dó–Ré–Dó, o Ré é uma bordadura",
    o2nom: "Apojatura",
    o2desc: "Nota estranha não preparada num tempo forte, resolvida por movimento conjunto descendente",
    o3nom: "Suspensão",
    o3desc: "A resolução de uma nota é retardada — a nota não estrutural mantém-se no tempo forte e resolve-se depois",
    schenkerWarn: "<strong>Erro clássico:</strong> Confundir redução schenkeriana com simplificação. A redução não elimina notas \"aleatoriamente\" — identifica as notas estruturais segundo critérios precisos (posição métrica, duração, papel harmónico). As notas ornamentais não são menos importantes: são a superfície expressiva. A redução revela a estrutura, não julga o valor.",
    motiviqueH2: "Análise motívica",
    motiviqueP: "A análise motívica identifica as células melódicas de 2 a 6 notas que constituem a matéria-prima de uma obra, e depois segue as suas transformações. Este nível de análise revela a unidade orgânica de uma composição — como tudo deriva de muito pouco.",
    beethInfoBox: "<strong>Beethoven — 5.ª Sinfonia:</strong> O motivo inicial (Sol–Fá–Sol–Mib) não é apenas o início do primeiro andamento. Este motivo rítmico (3 colcheias + semínima) e melódico (terça menor descendente) organiza os 4 andamentos completos — no tema do 2.º andamento, nas fanfarras do 3.º, na transição final do 4.º. É a própria definição de unidade orgânica.",
    beethCard: "Motivo Beethoven 5.ª — Sol–Sol–Sol–Mib",
    beethDesc: "Duas dimensões simultâneas: <strong>ritmo</strong> (curto–curto–curto–longo) e <strong>melodia</strong> (terça menor descendente). Ambas são inseparáveis na análise. No 2.º andamento o ritmo transforma-se, mas a terça melódica persiste.",
    motifOrigBtn: "▶ Motivo original",
    motifTransBtn: "▶ Transportado (mesmo ritmo)",
    transformH3: "4 transformações motívicas fundamentais",
    t0nom: "Transposição",
    t0desc: "O motivo transportado para outro grau — os intervalos são conservados",
    t0ex: "Beethoven 5.ª: motivo repetido a partir do 2.º compasso um tom mais baixo",
    t1nom: "Inversão",
    t1desc: "Os intervalos invertidos — o que subia desce agora e vice-versa",
    t1ex: "Bach: inversões do sujeito nas fugas",
    t2nom: "Aumentação",
    t2desc: "O motivo em valores duplos — mais lento, mais solene",
    t2ex: "Num registo mais agudo para marcar a aumentação",
    t3nom: "Fragmentação",
    t3desc: "Apenas as primeiras 2–3 notas do motivo — cria inquietação e urgência",
    t3ex: "Beethoven 5.ª: o desenvolvimento fragmenta as 4 notas em 2 + 2",
    labelOriginal: "Original:",
    labelTransforme: "Transformado:",
    labelExemple: "Exemplo:",
    methodeH3: "Método de análise motívica",
    s1label: "Identificar o motivo gerador",
    s1desc: "2 a 6 notas que aparecem no início e se repetem. Um intervalo ou ritmo distintivo é a chave.",
    s2label: "Cartografar as ocorrências",
    s2desc: "Marcar cada aparição do motivo na partitura — transposições e transformações incluídas.",
    s3label: "Analisar as transformações",
    s3desc: "Inversão, aumentação, diminuição, fragmentação, sequência. Como se desenvolve o motivo?",
    s4label: "Identificar a função estrutural",
    s4desc: "O motivo cria a exposição, o desenvolvimento, o clímax? Que papel narrativo desempenha?",
    brahmsInfoBox: "<strong>Brahms e a unidade motívica:</strong> Nos seus quartetos e sinfonias, Brahms deriva frequentemente toda a obra de um único intervalo (uma segunda ou uma terça). Este intervalo gerador aparece na melodia, no baixo, nas transições, nos contra-cantos — sempre reconhecível, sempre transformado. A análise motívica de Brahms revela uma densidade temática comparável à de Bach.",
    motiviqueWarn: "<strong>Erro frequente:</strong> Analisar cada acorde de superfície sem procurar a estrutura profunda. Dizer \"Dó–Sol–Fá–Dó\" não diz nada sobre a significação estrutural. A análise motívica complementa a análise harmónica: de um lado a estrutura vertical (acordes), do outro a estrutura horizontal (motivo e o seu destino). Ambas juntas revelam a lógica compositiva.",
    quizH2: "Quiz — Schenker e análise motívica",
  },
};

['fr','en','de','es','it','pt'].forEach(lang => {
  const path = `./messages/${lang}.json`;
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  if (!data.cours37) data.cours37 = {};
  // Merge narrative (keep existing maitreCard keys)
  data.cours37.narrative = { ...data.cours37.narrative, ...NARRATIVE[lang] };
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`${lang}: cours37.narrative now has ${Object.keys(data.cours37.narrative).length} keys`);
});
